README.md
doc/changelog.md
pom.xml
samples/cargo-jolokia-demo/pom.xml
samples/data-jolokia-demo/pom.xml
src/main/java/org/jolokia/docker/maven/config/RestartPolicy.java

fix RestartPolicy constructor

---

README.md
doc/changelog.md
doc/manual.md
pom.xml
samples/cargo-jolokia-demo/pom.xml
samples/data-jolokia-demo/pom.xml
src/main/java/org/jolokia/docker/maven/assembly/DockerAssemblyConfigurationSource.java
src/main/java/org/jolokia/docker/maven/assembly/DockerAssemblyManager.java
src/main/java/org/jolokia/docker/maven/assembly/DockerFileBuilder.java
src/main/java/org/jolokia/docker/maven/config/AssemblyConfiguration.java
src/main/java/org/jolokia/docker/maven/config/BuildImageConfiguration.java
src/main/resources/assemblies/empty.xml
src/test/java/org/jolokia/docker/maven/assembly/DockerAssemblyManagerTest.java
src/test/java/org/jolokia/docker/maven/config/handler/PropertyConfigHandlerTest.java

forgot to do this along side the volume enhancements, resolves #66.

allow the assembly configuration block to be optional

---

README.md
doc/changelog.md
pom.xml
samples/cargo-jolokia-demo/pom.xml
samples/data-jolokia-demo/pom.xml
src/main/java/org/jolokia/docker/maven/BuildMojo.java
src/main/java/org/jolokia/docker/maven/assembly/DockerAssemblyConfigurationSource.java
src/main/java/org/jolokia/docker/maven/util/MojoParameters.java
src/test/java/org/jolokia/docker/maven/assembly/DockerAssemblyConfigurationSourceTest.java

inject MavenFilterReader into BuildMojo

---

doc/intro.md

Just a bunch of spelling and wording fixes to make it a bit easier to read.

Fixed spelling and wording

---

src/main/java/org/jolokia/docker/maven/access/AuthConfig.java
src/main/java/org/jolokia/docker/maven/access/DockerAccessWithHttpClient.java

tested on https://github.com/docker/docker-registry/releases/tag/0.9.1

fix for issue #102

---

doc/manual.md
src/main/java/org/jolokia/docker/maven/assembly/DockerAssemblyManager.java
src/main/java/org/jolokia/docker/maven/config/AssemblyConfiguration.java

Change is not backward compatible: descriptor is renamed into descriptorFile
Signed-off-by: Oleg Sigida <oleg.sigida@gmail.com>

Adding ability to inline assembly into pom file (#157)

---

doc/changelog.md
doc/manual.md
pom.xml
src/main/java/org/jolokia/docker/maven/AbstractBuildSupporMojo.java
src/main/java/org/jolokia/docker/maven/WatchMojo.java
src/main/java/org/jolokia/docker/maven/access/DockerAccess.java
src/main/java/org/jolokia/docker/maven/access/UrlBuilder.java
src/main/java/org/jolokia/docker/maven/access/hc/DockerAccessWithHcClient.java
src/main/java/org/jolokia/docker/maven/config/BuildImageConfiguration.java
src/main/java/org/jolokia/docker/maven/config/handler/property/ConfigKey.java
src/main/java/org/jolokia/docker/maven/config/handler/property/PropertyConfigHandler.java
src/main/java/org/jolokia/docker/maven/model/Image.java
src/main/java/org/jolokia/docker/maven/service/BuildService.java
src/main/java/org/jolokia/docker/maven/service/QueryService.java
src/main/java/org/jolokia/docker/maven/service/ServiceHub.java
src/main/resources/META-INF/plexus/components.xml
src/test/java/org/jolokia/docker/maven/config/handler/property/PropertyConfigHandlerTest.java
src/test/java/org/jolokia/docker/maven/service/BuildServiceTest.java

better build cleanup 

---

.gitignore
doc/changelog.md
doc/manual.md
src/main/java/org/jolokia/docker/maven/BuildMojo.java
src/main/java/org/jolokia/docker/maven/config/BuildImageConfiguration.java
src/main/java/org/jolokia/docker/maven/config/ImageConfiguration.java
src/main/java/org/jolokia/docker/maven/config/RunImageConfiguration.java
src/main/java/org/jolokia/docker/maven/config/handler/property/ConfigKey.java
src/main/java/org/jolokia/docker/maven/config/handler/property/PropertyConfigHandler.java
src/main/java/org/jolokia/docker/maven/model/ContainerDetails.java
src/main/java/org/jolokia/docker/maven/model/ContainersListElement.java
src/main/java/org/jolokia/docker/maven/service/RunService.java
src/test/java/org/jolokia/docker/maven/config/handler/property/PropertyConfigHandlerTest.java
src/test/java/org/jolokia/docker/maven/model/ContainerTest.java

continuation of the original #225 request

issue 207 redux

---

doc/changelog.md
src/main/java/org/jolokia/docker/maven/access/hc/DockerAccessWithHcClient.java
src/main/java/org/jolokia/docker/maven/assembly/DockerAssemblyManager.java

- fixed 'NullPointerException' thrown when no assembly was specified
- only return first 12 of image id

resolves issue 236

---

doc/changelog.md
src/main/java/org/jolokia/docker/maven/service/ContainerTracker.java
src/test/java/org/jolokia/docker/maven/service/RunServiceTest.java
src/test/resources/docker/containerCreateConfigAll.json
src/test/resources/docker/containerHostConfigAll.json

- track alias names to container ids

resolves issue 182

---

src/main/java/org/jolokia/docker/maven/service/RunService.java

Fixes #323
Signed-off-by: Caspar Krieger &lt;email goes here&gt;
Replaces #324 .

Update dynamic host prop even without dynamic port prop

---

src/main/java/org/jolokia/docker/maven/access/DockerAccess.java
src/main/java/org/jolokia/docker/maven/access/UrlBuilder.java
src/main/java/org/jolokia/docker/maven/access/hc/DockerAccessWithHcClient.java
src/main/java/org/jolokia/docker/maven/config/BuildImageConfiguration.java
src/main/java/org/jolokia/docker/maven/config/handler/property/ConfigKey.java
src/main/java/org/jolokia/docker/maven/config/handler/property/PropertyConfigHandler.java
src/main/java/org/jolokia/docker/maven/service/BuildService.java
src/test/java/integration/DockerAccessIT.java
src/test/java/org/jolokia/docker/maven/config/handler/property/PropertyConfigHandlerTest.java
src/test/java/org/jolokia/docker/maven/service/BuildServiceTest.java

Signed-off-by: Eugen Cristea <eugen@cristea.org>

#348: no-cache flag implementation

---

doc/intro.md

found another one reading the docs :)

fix broken link

---

src/main/java/io/fabric8/maven/docker/util/ImageName.java
src/test/java/io/fabric8/maven/docker/util/ImageNameTest.java

allow multiple subcomponents in image names

---

src/main/java/io/fabric8/maven/docker/util/WaitUtil.java

Disable redirecting allow us to test http server before redirection.

Disable redirect in http wait

---

src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java

Fix DockerAccessWHC.removeNetwork exception msg

---

src/main/java/io/fabric8/maven/docker/StartMojo.java

Expose container properties of all images

---

src/main/asciidoc/inc/start/_network.adoc

Signed-off-by: Philip Wigg <phil@philipwigg.co.uk>

Mention the docker.autoCreateCustomNetworks on the networks doc

---

samples/pom.xml
src/main/resources/META-INF/plexus/components.xml

update samples aggregator pom; use build-nofork in lifecycles

---

doc/changelog.md
src/main/asciidoc/inc/_authentication.adoc
src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java
src/main/java/io/fabric8/maven/docker/access/AuthConfig.java
src/main/java/io/fabric8/maven/docker/access/ecr/AwsSigner4.java
src/main/java/io/fabric8/maven/docker/access/ecr/AwsSigner4Request.java
src/main/java/io/fabric8/maven/docker/access/ecr/EcrExtendedAuth.java
src/main/java/io/fabric8/maven/docker/util/AuthConfigFactory.java
src/test/java/io/fabric8/maven/docker/access/ecr/AwsSigner4RequestTest.java
src/test/java/io/fabric8/maven/docker/access/ecr/EcrExtendedAuthTest.java
src/test/java/io/fabric8/maven/docker/util/AuthConfigFatoryTest.java
src/test/java/io/fabric8/maven/docker/util/AuthConfigHandlerTest.java

AWS ECR key exchange
closes #637
replaces PR #646

Extended authentication

---

src/main/asciidoc/inc/_docker-build.adoc
src/main/asciidoc/inc/_docker-logs.adoc
src/main/asciidoc/inc/_docker-remove.adoc
src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java
src/main/java/io/fabric8/maven/docker/config/ConfigHelper.java
src/test/java/io/fabric8/maven/docker/log/DefaultLogCallbackTest.java

Replace docker.image with docker.filter in the docs

---

src/main/asciidoc/inc/build/_assembly.adoc

Just small fix within documentation

Fixed inline assembly example

---

doc/changelog.md
samples/helloworld/pom.xml
src/main/java/io/fabric8/maven/docker/config/ImageConfiguration.java
src/main/java/io/fabric8/maven/docker/service/BuildService.java
src/main/java/io/fabric8/maven/docker/util/ImageName.java
src/test/java/io/fabric8/maven/docker/service/RunServiceTest.java
src/test/java/io/fabric8/maven/docker/util/ImageNameTest.java

Minor image related fixes

---

doc/changelog.md
src/main/java/io/fabric8/maven/docker/assembly/DockerAssemblyManager.java

Fix issue with custom Dockerfile not properly added.

---

src/main/java/io/fabric8/maven/docker/access/KeyStoreUtil.java
src/test/java/io/fabric8/maven/docker/access/KeyStoreUtilTest.java
src/test/resources/io/fabric8/maven/docker/access/keys/ecdsa.pem

Add ECDSA encoded private key support.
Relates to #769.
Signed-off-by: Tobias Gesellchen <tobias@gesellix.de>

Add ECDSA support

---

src/main/asciidoc/inc/external/_property_configuration.adoc

Fix shmsize property

---

src/main/java/io/fabric8/maven/docker/config/ImageConfiguration.java
src/test/java/io/fabric8/maven/docker/config/ConfigHelperTest.java

Adding builder method to imageconfig

---

src/main/java/io/fabric8/maven/docker/config/handler/compose/DockerComposeConfigHandler.java
src/test/java/io/fabric8/maven/docker/config/handler/compose/DockerComposeConfigHandlerTest.java
src/test/resources/compose/docker-compose.yml
src/test/resources/compose/version/compose-no-version.yml
src/test/resources/compose/version/compose-version-2.yml
src/test/resources/compose/version/compose-version-2x.yml
src/test/resources/compose/version/compose-wrong-version.yml

And added some tests, too.
Fixes #818.

Fix docker-compose version handling

---

doc/changelog.md
src/main/asciidoc/inc/_docker-remove.adoc
src/main/java/io/fabric8/maven/docker/RemoveMojo.java

Address bug #193 Add support for removing tagged images according to the build.tag element
Signed-off-by: Alan Barrington-Hughes <alan.barrington.hughes@gmail.com>

#193 Add support for removing tagged images

---

src/main/java/io/fabric8/maven/docker/assembly/DockerAssemblyManager.java

Remove TODO comment in DockerAssemblyManager

---

src/main/asciidoc/inc/_docker-source.adoc
src/main/java/io/fabric8/maven/docker/SourceMojo.java

fix(documentation): Updated documentation of `docker:source`

---

src/main/java/io/fabric8/maven/docker/access/hc/ApacheHttpClientDelegate.java

Fixes issue https://github.com/fabric8io/docker-maven-plugin/issues/945
Signed-off-by: Stephen Fox <stephenfox995@hotmail.com>

Changed default headers in ApacheHttpClientDelegate#addDefaultHeaders

---

doc/changelog.md
src/main/java/io/fabric8/maven/docker/StartMojo.java

Signed-off-by: Jimmy Praet <jimmy.praet@ksz-bcss.fgov.be>

#970 postStart exec breakOnError should fail fast

---

src/main/java/io/fabric8/maven/docker/RemoveMojo.java
src/main/java/io/fabric8/maven/docker/VolumeRemoveMojo.java
src/main/java/io/fabric8/maven/docker/access/ContainerNetworkingConfig.java
src/main/java/io/fabric8/maven/docker/access/hc/win/NpipeConnectionSocketFactory.java
src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java
src/main/java/io/fabric8/maven/docker/config/DockerMachineConfiguration.java
src/main/java/io/fabric8/maven/docker/config/RegistryAuthConfiguration.java
src/main/java/io/fabric8/maven/docker/service/QueryService.java
src/main/java/io/fabric8/maven/docker/service/VolumeService.java
src/test/java/io/fabric8/maven/docker/access/ContainerHostConfigTest.java
src/test/java/io/fabric8/maven/docker/config/ImageConfigResolverTest.java
src/test/java/io/fabric8/maven/docker/config/UlimitConfigTest.java
src/test/java/io/fabric8/maven/docker/service/BuildServiceTest.java
src/test/java/io/fabric8/maven/docker/service/MojoExecutionServiceTest.java
src/test/java/io/fabric8/maven/docker/service/RunServiceTest.java
src/test/java/io/fabric8/maven/docker/util/DockerPathUtilTest.java
src/test/java/io/fabric8/maven/docker/util/ImageNameFormatterTest.java

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

Remove unused import

---

doc/changelog.md
samples/run-java/Dockerfile
samples/run-java/pom.xml
src/main/asciidoc/inc/build/_overview.adoc
src/main/java/io/fabric8/maven/docker/BuildMojo.java

Please see documentation for an explanation of this feature.

Introducing "dmp-plugins"

---

doc/changelog.md

Just a minor fix. Noticed while reading changelog.

Fix version in changelog for the latest release

---

samples/run-java/pom.xml
src/main/asciidoc/inc/build/_overview.adoc
src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java

chore: Respect the <run> section for a single image for the simple Dockerfile mode, too

---

doc/changelog.md
pom.xml
src/test/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClientTest.java
src/test/java/io/fabric8/maven/docker/assembly/DockerAssemblyManagerTest.java
src/test/java/io/fabric8/maven/docker/service/MojoExecutionServiceTest.java
src/test/java/io/fabric8/maven/docker/service/RunServiceTest.java
src/test/java/io/fabric8/maven/docker/util/AuthConfigFactoryTest.java
src/test/java/io/fabric8/maven/docker/util/DockerFileUtilTest.java
src/test/java/io/fabric8/maven/docker/util/ImageNameFormatterTest.java

Update to JMockit 1.40

---

src/main/asciidoc/inc/_docker-volume-create.adoc

Just gave this example a try and maven reported a parsing problem because of this closing tag. :)

Minor fix on volume configuration example

---

src/main/java/io/fabric8/maven/docker/access/AuthConfig.java
src/test/java/io/fabric8/maven/docker/util/AuthConfigTest.java

Thanks for the quick merge in #1084, @rhuss!
I took another look today and was quite embarrassed to see I swapped `/` and `_`, so this fixes that. Sorry for the PR spam! :blush:

Follow-up on X-Registry-Auth encoding fix

---

src/main/java/io/fabric8/maven/docker/VolumeCreateMojo.java
src/main/java/io/fabric8/maven/docker/VolumeRemoveMojo.java
src/test/java/io/fabric8/maven/docker/VolumeCreateMojoTest.java
src/test/java/io/fabric8/maven/docker/VolumeRemoveMojoTest.java

Fixes https://github.com/fabric8io/docker-maven-plugin/issues/1086

fixes #1086 NullpointerException

---

doc/changelog.md
src/main/asciidoc/inc/_authentication.adoc
src/main/java/io/fabric8/maven/docker/util/AuthConfigFactory.java
src/test/java/io/fabric8/maven/docker/util/AuthConfigFactoryTest.java

Keeping config.json under user home is a problem on CI (e.g. Jenkins)

Respect DOCKER_CONFIG when looking for config.json

---

doc/changelog.md
src/main/java/io/fabric8/maven/docker/StartMojo.java
src/main/java/io/fabric8/maven/docker/StopMojo.java
src/main/java/io/fabric8/maven/docker/service/RunService.java
src/main/java/io/fabric8/maven/docker/util/CredentialHelperClient.java

We really need integration tests!

fix: Various regression fixes

---

pom.xml

Contains fix : https://issues.apache.org/jira/browse/SUREFIRE-1588
which was causing build failures on CircleCi

Chore: Upgrade to surefire 3.0.0-M1

---

src/main/java/io/fabric8/maven/docker/StartMojo.java
src/main/java/io/fabric8/maven/docker/service/helper/StartContainerExecutor.java
src/test/java/io/fabric8/maven/docker/service/helper/StartContainerExecutorTest.java

Issue #1111: Provide container properties to the wait configuration execution

---

doc/changelog.md
src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java

Closing API version request connection
Fix #1152

close api version http connection

---

src/main/asciidoc/inc/build/_configuration.adoc
src/main/java/io/fabric8/maven/docker/assembly/DockerFileBuilder.java
src/main/java/io/fabric8/maven/docker/assembly/DockerFileKeyword.java
src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java
src/main/java/io/fabric8/maven/docker/config/handler/property/ConfigKey.java
src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
src/test/java/io/fabric8/maven/docker/assembly/DockerFileBuilderTest.java
src/test/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandlerTest.java
src/test/resources/docker/Dockerfile.test

Support docker SHELL setting for runCmds

---

doc/changelog.md
src/main/java/io/fabric8/maven/docker/service/BuildService.java
src/main/java/io/fabric8/maven/docker/util/AuthConfigFactory.java
src/main/java/io/fabric8/maven/docker/util/DockerFileUtil.java

Make BuildService read local ~/.docker/config.json directory and fetch
proxy settings.
Fixes #1148

Fix #1148: Proxy settings are ignored (initial draft)

---

doc/changelog.md
src/main/java/io/fabric8/maven/docker/util/AuthConfigFactory.java
src/main/java/io/fabric8/maven/docker/util/CredentialHelperClient.java
src/test/java/io/fabric8/maven/docker/util/AuthConfigFactoryTest.java

fix(auth): Non existing version command on credential helper is ignored

---

doc/changelog.md
samples/dockerfile/pom.xml
src/main/asciidoc/inc/build/_overview.adoc
src/main/java/io/fabric8/maven/docker/assembly/DockerAssemblyManager.java
src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java
src/main/java/io/fabric8/maven/docker/config/ConfigHelper.java
src/main/java/io/fabric8/maven/docker/config/handler/property/ConfigKey.java
src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
src/test/java/io/fabric8/maven/docker/config/BuildImageConfigurationTest.java
src/test/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandlerTest.java

This is the continuation of #995

Added 'contextDir' configuration option. Used to specify Docker build context

---

doc/changelog.md
pom.xml
src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java
src/test/java/io/fabric8/maven/docker/config/BuildImageConfigurationTest.java
src/test/java/io/fabric8/maven/docker/config/BuildImageConfigurationWithMavenDepsTest.java

Fix #1200 
Fixed my mistake. This is based upon suspicion seeing the stack trace provided by the user. I am still not able to reproduce this exception.

Fix #1200: NullPointerException in BuildImageConfiguration

---

doc/changelog.md
src/main/java/io/fabric8/maven/docker/access/BuildOptions.java
src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java
src/main/java/io/fabric8/maven/docker/service/BuildService.java
src/test/java/io/fabric8/maven/docker/access/BuildConfigTest.java

Fix #1030: docker:build does not support 'network' option

---

doc/changelog.md
src/main/java/io/fabric8/maven/docker/util/DockerFileUtil.java
src/test/java/io/fabric8/maven/docker/util/DockerFileUtilTest.java
src/test/resources/io/fabric8/maven/docker/util/Dockerfile_multi_stage_named_build_stages
src/test/resources/io/fabric8/maven/docker/util/Dockerfile_multi_stage_named_redundant_build_stages

Fix #1264: Failure referencing a previous staged image in FROM clause

---

doc/changelog.md
src/main/java/io/fabric8/maven/docker/config/LogConfiguration.java
src/test/java/io/fabric8/maven/docker/config/LogConfigurationTest.java

I.e. when enabled is a Boolean but not identical to Boolean.TRUE

fix: Error in boolean check which prevents logging sometimes

---

src/main/java/io/fabric8/maven/docker/util/EnvUtil.java

Make outputDirectory work with absolute path

---

src/main/java/io/fabric8/maven/docker/util/aws/AwsSdkAuthConfigFactory.java

Improve reporting of errors relating to AWS authentication

---

src/main/java/io/fabric8/maven/docker/util/EnvUtil.java

fixed issue: #1359

---

src/main/java/io/fabric8/maven/docker/service/RegistryService.java
src/test/java/io/fabric8/maven/docker/service/RegistryServiceTest.java

Fix #1380 (including test)

---

pom.xml
src/main/java/io/fabric8/maven/docker/util/JibServiceUtil.java
src/test/java/io/fabric8/maven/docker/util/JibServiceUtilTest.java

jib-core 0.15.0 is the latest version.

upgrade to jib-core 0.15.0

---

.github/workflows/windows-build.yml
src/test/java/io/fabric8/maven/docker/service/JibBuildServiceTest.java
src/test/java/io/fabric8/maven/docker/util/JibServiceUtilTest.java

Fix OS specific filesystem assumptions in the tests

Fix build on Windows

---

src/main/asciidoc/inc/misc/_startup.adoc

Fixes #1449.
Signed-off-by: Adam Holley <adam.holley@cubic.com>

Issue #1449: Fix case for entryPoint examples in documentation.

---

doc/changelog.md
src/main/asciidoc/inc/external/_property_configuration.adoc
src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
src/test/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandlerTest.java

Extract `cacheFrom` from original BuildImageConfiguration as a LIST instead of STRING

---

doc/changelog.md
pom.xml
samples/spring-boot-with-jib/pom.xml
src/main/java/io/fabric8/maven/docker/util/JibServiceUtil.java

+ Update Guava to 30.1-jre
+ Update Jib-Core to 0.18.0

Update Guava to 30.1-jre and Jib-Core to 0.18.0

---

.circleci/config.yml
pom.xml

Somehow sonar doesn't seem to be working. I'm not able to see it reporting coverage/code smells on Pull requests

Chore: Fix Sonar CircleCi Job

---

src/main/java/io/fabric8/maven/docker/access/log/LogRequestor.java

Revert part of #965 to fix #1103

---

src/main/java/io/fabric8/maven/docker/access/log/LogRequestor.java

Wait for request.abort to finish before calling is.close();

---

src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java

Signed-off-by: Oleksandr Volynets <oleksandr.volynets@gmail.com>

Added the missing assembly name to the log placeholder

---

doc/changelog.md
src/main/asciidoc/inc/_docker-stop.adoc
src/main/java/io/fabric8/maven/docker/StopMojo.java

Follow-up PR for #1492 
+ Add `executeStopOnVMShutdown` flag documentation
+ Fix sonar security hotspot reports related to pull request

Followup #1492: Add asciidoc for executeStopOnVMShutdown flag in StopMojo

---

doc/changelog.md
src/main/java/io/fabric8/maven/docker/service/JibBuildService.java
src/main/java/io/fabric8/maven/docker/util/JibServiceUtil.java
src/test/java/io/fabric8/maven/docker/service/JibBuildServiceTest.java
src/test/java/io/fabric8/maven/docker/util/JibServiceUtilTest.java

Revert #1498

---

doc/changelog.md
src/main/java/io/fabric8/maven/docker/service/RegistryService.java
src/test/java/io/fabric8/maven/docker/service/RegistryServiceTest.java

Revert 1496

---

doc/changelog.md
src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java
src/main/java/io/fabric8/maven/docker/BuildMojo.java
src/main/java/io/fabric8/maven/docker/PushMojo.java
src/test/java/io/fabric8/maven/docker/PushMojoTest.java

Fix #1482
Move skipPom handling code to AbstractDockerMojo

Fix #1482: SkipPom is ignored by push goal

---

src/main/asciidoc/inc/external/_property_configuration.adoc
src/main/asciidoc/inc/start/_configuration.adoc
src/main/java/io/fabric8/maven/docker/access/ContainerHostConfig.java
src/main/java/io/fabric8/maven/docker/config/RunImageConfiguration.java
src/main/java/io/fabric8/maven/docker/config/handler/compose/DockerComposeConfigHandler.java
src/main/java/io/fabric8/maven/docker/config/handler/compose/DockerComposeServiceWrapper.java
src/main/java/io/fabric8/maven/docker/config/handler/property/ConfigKey.java
src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
src/main/java/io/fabric8/maven/docker/service/RunService.java
src/test/java/io/fabric8/maven/docker/config/handler/AbstractConfigHandlerTest.java
src/test/java/io/fabric8/maven/docker/config/handler/compose/DockerComposeConfigHandlerTest.java
src/test/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandlerTest.java
src/test/java/io/fabric8/maven/docker/service/RunServiceTest.java
src/test/resources/compose/docker-compose.yml
src/test/resources/docker/containerCreateConfigAll.json
src/test/resources/docker/containerHostConfigAll.json

Support for docker run --sysctl parameters

---

it/buildx-contextdir/Dockerfile
it/buildx-contextdir/docker/Dockerfile
it/buildx-contextdir/docker/resource.properties
it/buildx-contextdir/pom.xml
it/buildx-contextdir/src/docker/Dockerfile
it/buildx-contextdir/src/docker/resource.properties
it/buildx-dependencyset/Dockerfile
it/buildx-dependencyset/docker/script.sh
it/buildx-dependencyset/pom.xml
it/buildx-dependencyset/src/main/java/org/example/Main.java
it/buildx-dockerfile/pom.xml
it/buildx-dockerfile/src/main/Dockerfile
it/buildx-dockerfile/src/main/java/org/example/Main.java
it/buildx/pom.xml
it/buildx/src/main/java/io/fabric8/dmp/sample/multiarch/helloworld/App.java
it/docker/Dockerfile
it/docker/resource.properties
it/pom.xml
src/main/java/io/fabric8/maven/docker/BuildMojo.java
src/main/java/io/fabric8/maven/docker/assembly/DockerAssemblyManager.java
src/main/java/io/fabric8/maven/docker/config/ArchiveCompression.java
src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java
src/main/java/io/fabric8/maven/docker/service/BuildXService.java
src/main/java/io/fabric8/maven/docker/service/ServiceHub.java
src/test/java/io/fabric8/maven/docker/BuildMojoTest.java
src/test/java/io/fabric8/maven/docker/MojoTestBase.java
src/test/java/io/fabric8/maven/docker/service/RegistryServiceTest.java

buildx does not work when specifying Dockerfile location

---

it/buildx/pom.xml
src/main/java/io/fabric8/maven/docker/service/BuildXService.java
src/test/java/io/fabric8/maven/docker/service/RegistryServiceTest.java

correct buildx tags

---

src/main/java/io/fabric8/maven/docker/access/AuthConfig.java

Use https://index.docker.io/v1/ as default server registry

---

doc/changelog.md
pom.xml

deps : Update jib-core to v0.23.0

---

.gitignore
it/platform-run/pom.xml
it/pom.xml
src/main/asciidoc/inc/start/_configuration.adoc
src/main/java/io/fabric8/maven/docker/access/ContainerCreateConfig.java
src/main/java/io/fabric8/maven/docker/access/UrlBuilder.java
src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java
src/main/java/io/fabric8/maven/docker/config/RunImageConfiguration.java
src/main/java/io/fabric8/maven/docker/config/handler/property/ConfigKey.java
src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
src/main/java/io/fabric8/maven/docker/service/RunService.java
src/test/java/io/fabric8/maven/docker/UrlBuilderTest.java
src/test/java/io/fabric8/maven/docker/access/ContainerCreateConfigTest.java
src/test/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandlerTest.java

Support --platform argument for docker start

---

src/main/java/io/fabric8/maven/docker/config/BuildXConfiguration.java

@rohanKanojia - this update makes the platform elements behave as documented.

split platforms by comma as documented

---

src/main/asciidoc/inc/build/_buildx.adoc
src/main/java/io/fabric8/maven/docker/config/AttestationConfiguration.java
src/main/java/io/fabric8/maven/docker/config/BuildXConfiguration.java
src/main/java/io/fabric8/maven/docker/config/handler/property/ConfigKey.java
src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
src/main/java/io/fabric8/maven/docker/service/BuildXService.java
src/test/java/io/fabric8/maven/docker/BuildMojoTest.java
src/test/java/io/fabric8/maven/docker/service/RegistryServiceTest.java

BuildX attestation configuration

---

src/main/java/io/fabric8/maven/docker/access/ContainerCreateConfig.java
src/main/java/io/fabric8/maven/docker/access/ContainerHostConfig.java
src/main/java/io/fabric8/maven/docker/util/EnvUtil.java
src/test/java/io/fabric8/maven/docker/access/ContainerCreateConfigTest.java
src/test/java/io/fabric8/maven/docker/access/ContainerHostConfigTest.java
src/test/java/io/fabric8/maven/docker/util/EnvUtilTest.java

Fixes #1719 #1713
After my fix, the sample provided in #1719 works.

Fix Windows volume bindings for Rancher, Podman and Windows-based containers

---

CONTRIBUTING.md
doc/intro.md

@rhuss @rohanKanojia , I accidentally deleted my root repository.
- I fixed some typos in ```intro.md``` and ```CONTRIBUTING.md```
- I did not change any phrases in ```Developer Certificate```.
If you guys had any issues please comment.
Signing-off-by: Mohamed Abdullah <abdullahfakrudeen2020@gmail.com>

Fixed Typos in intro.md and CONTRIBUTING.md

---

src/test/java/io/fabric8/maven/docker/service/ArchiveServiceTest.java

Dear maintainers,
I wanted to inform you that I have removed the unused import from the ArchieveServicetest.
Best regards,
F Mohamed Abdullah

Fix: ArchieveServiceTest issue1743

---

src/test/java/io/fabric8/maven/docker/service/RegistryServiceTest.java

Dear Rohan,
I have made the changes you requested. The `hasImage` and `dockerFileUtilMockedStatic` fields have been removed. Additionally, the `givenHasImage()` method has been eliminated. After implementing these changes, the `RegistryServiceTest` also passed successfully.
Best regards,
F Mohamed Abdullah

Fix: RegistryServiceTest : remove unused variable `hasImage` and `dockerFileUtilMockedStatic`  issue1766

---

it/spring-boot-with-jib/pom.xml
it/spring-boot-with-jib/src/main/java/io/fabric8/maven/sample/springboot/jib/HelloController.java

@rohanKanojia, Please review this and merge this.

Quickstarts: Improve it/spring-boot-with-jib integration test

---

src/main/asciidoc/inc/build/_buildx.adoc

Make description easier to understand and add a link to integration tests as examples.

Improve documentation for adding build secrets

---

.github/workflows/sonar-pr-analysis-publish.yml
pom.xml

+ Bump `com.github.jnr:jnr-unixsocket` to `0.38.23`

chore (deps) : bump jnr-unixsocket to v0.38.23
