fabric8io/docker-maven-plugin

- src/main/java/org/jolokia/docker/maven/access/DockerAccessWithHttpClient.java
containers tagged with `latest` are not properly handled by the `docker:stop` goal.
> fix for stopping containers using the 'latest' tag

- README.md
- doc/changelog.md
- doc/manual.md
- pom.xml
- samples/cargo-jolokia-demo/pom.xml
- samples/data-jolokia-demo/pom.xml
- src/main/java/org/jolokia/docker/maven/access/PortMapping.java
- src/test/java/org/jolokia/docker/maven/access/PortMappingTest.java
this lets me manage manage bind hosts in different environments by way of `/etc/hosts` / dns instead of overriding maven properties.
docker won't bind to the address if it's not on the host, so specifying an invalid host name is the same as giving an incorrect ip.
> allow hostnames to be specified in port configuration

- README.md
- doc/changelog.md
- doc/manual.md
- pom.xml
- samples/cargo-jolokia-demo/pom.xml
- samples/data-jolokia-demo/pom.xml
- src/main/java/org/jolokia/docker/maven/AbstractDockerMojo.java
- src/main/java/org/jolokia/docker/maven/BuildMojo.java
- src/main/java/org/jolokia/docker/maven/PushMojo.java
- src/main/java/org/jolokia/docker/maven/access/DockerAccess.java
- src/main/java/org/jolokia/docker/maven/access/DockerAccessWithHttpClient.java
- src/main/java/org/jolokia/docker/maven/config/BuildImageConfiguration.java
- src/main/java/org/jolokia/docker/maven/util/ImageName.java
This may not be complete and might just be a starting point for discussions.
> Tagging during build/push

- README.md
- doc/changelog.md
- pom.xml
- samples/cargo-jolokia-demo/pom.xml
- samples/data-jolokia-demo/pom.xml
- src/main/java/org/jolokia/docker/maven/BuildMojo.java
- src/main/java/org/jolokia/docker/maven/assembly/DockerAssemblyConfigurationSource.java
- src/main/java/org/jolokia/docker/maven/assembly/DockerAssemblyManager.java
- src/main/java/org/jolokia/docker/maven/util/EnvUtil.java
- src/test/java/org/jolokia/docker/maven/assembly/DockerAssemblyConfigurationSourceTest.java
> append $basedir to all output directory paths

- doc/changelog.md
- doc/manual.md
- src/main/resources/assemblies/artifact-with-dependencies.xml
- src/main/resources/assemblies/artifact.xml
> allow easy overriding of project artifact name when using pre-packaged descriptors

- doc/changelog.md
- doc/manual.md
- src/main/java/org/jolokia/docker/maven/StartMojo.java
- src/main/java/org/jolokia/docker/maven/access/DockerAccess.java
- src/main/java/org/jolokia/docker/maven/access/DockerAccessWithHttpClient.java
- src/main/java/org/jolokia/docker/maven/access/UrlBuilder.java
- src/main/java/org/jolokia/docker/maven/config/RunImageConfiguration.java
- src/main/java/org/jolokia/docker/maven/config/handler/property/ConfigKey.java
- src/main/java/org/jolokia/docker/maven/config/handler/property/PropertyConfigHandler.java
- src/test/java/integration/DockerAccessIT.java
- src/test/java/org/jolokia/docker/maven/config/handler/PropertyConfigHandlerTest.java
- allow container to be named using `alias` when created/started
> allow containers to be named using its 'alias' 

- pom.xml
- src/main/java/org/jolokia/docker/maven/StartMojo.java
- src/main/java/org/jolokia/docker/maven/access/ContainerCreateConfig.java
- src/test/java/org/jolokia/docker/maven/StartMojoContainerConfigsTest.java
- src/test/java/org/jolokia/docker/maven/assembly/DockerAssemblyConfigurationSourceTest.java
I had a need for port/parameter substitution in environment variables. I wanted to set the database URL on my second container, that had the port as determined for the first container.
E.g., the second container had something like this:
<env>
<DATABASE_URL>jdbc\:mysql\://${env.DOCKER_HOST_HOST}:${database.port}/</DATABASE_URL>
</env>
The code in the merge request does this, plus a few minor other snippets.
> Do port/parameter substitution in environment variables

- src/main/java/org/jolokia/docker/maven/assembly/DockerAssemblyManager.java
- src/main/resources/assemblies/rootWar.xml
- src/test/java/org/jolokia/docker/maven/assembly/DockerAssemblyConfigurationSourceTest.java
The temporary assembly is now outputdir/build/maven.tgz instead of a directory (was outputdir/build/maven/
Aim to fix the files/directory rights defined in assembly issue which appear for some windows users.
The problem is that the fat/ntfs or any other file systeme like this ones which does not support linux like rights)
The solution is to use a system that does not rely on underling File system. choosen to use tgz archive.
Fixed some unit test issues under windows.
> Output to dir is now an archive.

- src/main/java/org/jolokia/docker/maven/StartMojo.java
Previous behavior only allowed project properties to override them.
Even the documentation suggested that you could override them by passing
-Dfoo=bar on the mvn cli, but this wasn't actually the case.
Signed-off-by: Ben Reser <ben.reser@cdk.com>
> Allow dynamic ports to be override by System properties.

- src/main/java/org/jolokia/docker/maven/access/log/LogRequestor.java
Hi,
I was getting log messages being cut off in the build:
[ERROR] DOCKER> Invalid log format for '201' (expected: "<timestamp> <txt>")
I switched this method:
https://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html#read(byte[],%20int,%20int)
"An attempt is made to read as many as len bytes, but a smaller number may be read. The number of bytes actually read is returned as an integer."
for this method:
https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/IOUtils.html#read(java.io.InputStream, byte[], int, int)
"This implementation guarantees that it will read as many bytes as possible before giving up"
Cheers,
Dan
> Fix log messages getting cut off in the build

- src/main/java/org/jolokia/docker/maven/access/chunked/BuildResponseHandler.java
- src/main/java/org/jolokia/docker/maven/access/chunked/ChunkedResponseHandler.java
- src/main/java/org/jolokia/docker/maven/access/chunked/ChunkedResponseReader.java
- src/main/java/org/jolokia/docker/maven/access/chunked/PullOrPushResponseHandler.java
- src/main/java/org/jolokia/docker/maven/access/chunked/TextToJsonBridgeCallback.java
This is a pull request to fix this issue: https://github.com/rhuss/docker-maven-plugin/issues/167
I saw that there was already some processing around chunked responses to parse them and log their messages. This just takes it one small step further and throws an exception if the chucked response contains an error (effectively causing the plugin execution to fail).
> Chunked response errors should fail plugin execution

- src/main/java/org/jolokia/docker/maven/access/log/LogRequestor.java
Some application tend to dump huge log string (eg. a list of all system variables) for debug purpouses. These log exceeds the predefined buffer length of 8129. I think that the buffer should be created dynamically per line.
> fixed an issue (ArrayOutOfBoundException) with long log lines

- doc/manual.md
- pom.xml
- src/main/java/org/jolokia/docker/maven/BuildMojo.java
- src/main/java/org/jolokia/docker/maven/StartMojo.java
- src/main/java/org/jolokia/docker/maven/assembly/DockerAssemblyManager.java
- src/main/java/org/jolokia/docker/maven/assembly/DockerFileBuilder.java
- src/main/java/org/jolokia/docker/maven/config/Arguments.java
- src/main/java/org/jolokia/docker/maven/config/BuildImageConfiguration.java
- src/main/java/org/jolokia/docker/maven/config/RunImageConfiguration.java
- src/main/java/org/jolokia/docker/maven/config/handler/property/ConfigKey.java
- src/main/java/org/jolokia/docker/maven/config/handler/property/PropertyConfigHandler.java
- src/test/java/org/jolokia/docker/maven/StartMojoContainerConfigsTest.java
- src/test/java/org/jolokia/docker/maven/assembly/DockerFileBuilderTest.java
- src/test/java/org/jolokia/docker/maven/config/handler/property/PropertyConfigHandlerTest.java
introduced cmd and entrypoint with exec and shell form support.
the change is not backward compatible to the previous version.
Signed-off-by: Oleg Sigida <oleg.sigida@gmail.com>
> Add CMD and ENTRYPOINT (fixes #130)

- README.md
Changed "The current version ist" to "The current version is".
Signed-off-by: Jared Petersen <jpetersen11@wou.edu>
> Fixed misspelling in README

- doc/intro.md
- doc/manual.md
the 'command' configuration parameter has been replaced by 'cmd' since v0.12.0
fixes #243
> fix docs: replace 'command' by 'cmd' (since v0.12.0)

- doc/changelog.md
- doc/manual.md
- src/main/java/org/jolokia/docker/maven/StartMojo.java
- src/main/java/org/jolokia/docker/maven/WatchMojo.java
- src/main/java/org/jolokia/docker/maven/access/DockerAccess.java
- src/main/java/org/jolokia/docker/maven/access/UrlBuilder.java
- src/main/java/org/jolokia/docker/maven/access/hc/DockerAccessWithHcClient.java
- src/main/java/org/jolokia/docker/maven/config/WaitConfiguration.java
- src/main/java/org/jolokia/docker/maven/config/handler/property/ConfigKey.java
- src/main/java/org/jolokia/docker/maven/config/handler/property/PropertyConfigHandler.java
- src/main/java/org/jolokia/docker/maven/service/RunService.java
- src/main/java/org/jolokia/docker/maven/service/ShutdownAction.java
- src/test/java/integration/DockerAccessIT.java
- src/test/java/org/jolokia/docker/maven/config/handler/property/PropertyConfigHandlerTest.java
- src/test/java/org/jolokia/docker/maven/service/ShutdownActionTest.java
PR for #266
e.g. 
```
<wait>
<http>
<url>http://localhost:${host.port}</url>
<method>GET</method>
<status>200..399</status>
</http>
<time>10000</time>
<shutdown>500</shutdown>
<exec>
<postStart>/opt/init_db.sh<postStart>
<preStop>/opt/notify_end.sh</preStop>
</exec>
</wait>
```
> Add logic to specify exec commands during postStart and preStop

- doc/manual.md
- src/main/java/org/jolokia/docker/maven/access/DockerAccess.java
- src/main/java/org/jolokia/docker/maven/access/UrlBuilder.java
- src/main/java/org/jolokia/docker/maven/access/hc/DockerAccessWithHcClient.java
- src/main/java/org/jolokia/docker/maven/config/WaitConfiguration.java
- src/main/java/org/jolokia/docker/maven/config/handler/property/ConfigKey.java
- src/main/java/org/jolokia/docker/maven/config/handler/property/PropertyConfigHandler.java
- src/main/java/org/jolokia/docker/maven/service/ContainerTracker.java
- src/main/java/org/jolokia/docker/maven/service/RunService.java
- src/test/java/integration/DockerAccessIT.java
- src/test/java/org/jolokia/docker/maven/service/RunServiceTest.java
Sets the delay between docker stop and kill. This resolves #293
Signed-off-by: Florian Merz <florian.merz@goeuro.com>
> add killafter parameter to image:run:wait

- src/main/java/org/jolokia/docker/maven/util/WaitUtil.java
WaitUtil has it's own retry mechanism and by disabling the HTTP Client retries it is easier to debug issues with containers starting.
Also HTTP Client retries provide superfluous logging considering it is highly likely the system will be unavailable when the first check occurs.
Signed-off-by: James Baker <james@brighthelix.co.uk>
> Disable Apache HTTP Client retry in WaitUtil

- doc/manual/docker-start.md
- src/main/java/org/jolokia/docker/maven/StartMojo.java
- src/main/java/org/jolokia/docker/maven/config/WaitConfiguration.java
- src/main/java/org/jolokia/docker/maven/config/handler/property/ConfigKey.java
- src/main/java/org/jolokia/docker/maven/config/handler/property/PropertyConfigHandler.java
- src/main/java/org/jolokia/docker/maven/model/Container.java
- src/main/java/org/jolokia/docker/maven/model/ContainerDetails.java
- src/main/java/org/jolokia/docker/maven/model/ContainersListElement.java
- src/main/java/org/jolokia/docker/maven/util/WaitUtil.java
- src/test/java/org/jolokia/docker/maven/util/WaitUtilTest.java
Example:
```xml
<wait>
<time>60000</time>
<tcp>
<ports>
<port>3306</port>
<port>9999</port>
</ports>
</wait>
```
This will setup a TCP port checker for ports 3306 and 9999. The test will time out after 60 seconds and the poll interval is hard coded, just like the HTTP wait condition.
This configuration differs from the proposed one in the issue #304:
* I remove the `<interval>` property, because this is already hardcoded with `org.jolokia.docker.maven.util.WaitUtil#WAIT_RETRY_WAIT` in `org.jolokia.docker.maven.util.WaitUtil#wait()`.
* Added support for multiple port checks.
> Added support for TCP port wait condition

- src/main/java/org/jolokia/docker/maven/util/AuthConfigFactory.java
- src/test/java/org/jolokia/docker/maven/util/AuthConfigHandlerTest.java
Judging the [docs](https://docs.docker.com/engine/reference/commandline/tag/) the name of the image contains the registry host rather then the full url.
For ex.: my.super.registry.com:443/images
But in the config.json there is usually full address with the http scheme:
```json
{
"auths": {
"https://my.super.registry.com": {
"auth": "my_auth",
"email": "none"
}
}
}
```
> Check for repository with 'https://' scheme

- doc/manual/global-configuration.md
Fixed one of the links in the global configuration md file, but there are still broken ones. Specifically the "Port Mapping" and "Log Configuration".
> Fixed documentation links

- doc/intro.md
- doc/manual/docker-start.md
- doc/manual/global-configuration.md
The documentation referring to the deprecated boot2docker software makes the plugin sound dated even though it works fine with docker-machine.  I think this pull request addresses the intent of issue #264
> #264, update references to boot2docker to include docker-machine

- pom.xml
- samples/cargo-jolokia-demo/pom.xml
- samples/data-jolokia-demo/pom.xml
- src/main/resources/META-INF/plexus/components.xml
Add docker packaging.  This eliminates much boilerplate configuration.
> Docker lifecycle

- doc/manual/docker-build.md
Maven uses basedir not baseDir or basedDir
> Spelling fixes

- src/main/java/io/fabric8/maven/docker/access/log/LogRequestor.java
- src/test/java/io/fabric8/maven/docker/access/log/LogRequestorTest.java
> Refactor stream parsing to ensure safety.

- doc/manual/external-configuration.md
- doc/manual/global-configuration.md
- src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java
- src/main/java/io/fabric8/maven/docker/access/UrlBuilder.java
- src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java
- src/main/java/io/fabric8/maven/docker/config/RunImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/ConfigKey.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
- src/main/java/io/fabric8/maven/docker/service/QueryService.java
- src/main/java/io/fabric8/maven/docker/service/ServiceHub.java
- src/main/java/io/fabric8/maven/docker/service/ServiceHubFactory.java
Signed-off-by: Gregory Gulrajani <gregory.gulrajani@nucleusfinancial.com>
> docker container fetch limit is now configurable

- doc/changelog.md
- src/main/asciidoc/inc/_global-configuration.adoc
- src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java
- src/main/java/io/fabric8/maven/docker/service/QueryService.java
- src/main/java/io/fabric8/maven/docker/util/AutoPullMode.java
- src/test/java/io/fabric8/maven/docker/service/QueryServiceAutoPullTest.java
resolves #504 and allows images to be auto-pulled once for an entire build.
> - add support for pulling an image once per (reactor) build

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/PushMojo.java
- src/main/java/io/fabric8/maven/docker/access/DockerAccess.java
- src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java
- src/test/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClientTest.java
i went to update the docs to add the `retryCount` parameter and now i can't find them...
> allow retries of a failed docker:push (resolves #508)

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/service/RunService.java
- src/main/java/io/fabric8/maven/docker/util/WaitUtil.java
- src/test/java/io/fabric8/maven/docker/service/RunServiceTest.java
- src/test/java/io/fabric8/maven/docker/util/WaitUtilTest.java
resolves #518, now the plugin will continue as soon as the container stops, hurray faster builds!
> - run 'stopContainer' in a Future (resolves #518)

- src/main/java/io/fabric8/maven/docker/StartMojo.java
- src/main/java/io/fabric8/maven/docker/model/Container.java
- src/main/java/io/fabric8/maven/docker/model/ContainerDetails.java
- src/main/java/io/fabric8/maven/docker/model/ContainersListElement.java
This adds property mappings for custom networks, using the format: 
```
docker.container.<alias>.net.<name>.ip
```
It seems important when the build is running on a container, and tries to start other containers in order to use them as remote services for integration testing. In this case, the only way I've found success is by using a custom network created using:
```
$ docker network create -d bridge ci-network
```
My Jenkins instance is running in its own docker container, so the bridge aspect allows me access to Jenkins. All the docker containers started by Jenkins will also need to use this custom network, I've found, and when the build needs to access them it can use the container's IP address on the custom network along with the ports from the EXPOSE line in the Dockerfile (not …
> Add custom network IP address property mappings

- src/main/java/io/fabric8/maven/docker/access/DockerConnectionDetector.java
- src/main/java/io/fabric8/maven/docker/access/hc/ApacheHttpClientDelegate.java
- src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java
- src/main/java/io/fabric8/maven/docker/access/hc/win/NamedPipe.java
- src/main/java/io/fabric8/maven/docker/access/hc/win/NamedPipeClientBuilder.java
- src/main/java/io/fabric8/maven/docker/access/hc/win/NpipeSocketAddress.java
- src/main/java/io/fabric8/maven/docker/access/hc/win/WindowsConnectionSocketFactory.java
- src/test/java/integration/DockerAccessWinIT.java
- src/test/java/io/fabric8/maven/docker/access/DockerConnectionDetectorTest.java
- src/test/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClientTest.java
This PR adds support for new Docker for Windows on Windows 10 (not docker toolbox, see https://docs.docker.com/engine/installation/windows/). This version of docker exposes api through windows named pipe //./pipe/docker_engine. Currently yours maven plugin don't support this condition. 
I added support for it, it's work at my machine, but you must set new configuration property "docker.machine.ignoreEmpty" to true, because windows docker don't expose any docker machine after installation.
> Add support for "Docker for Windows"

- src/main/java/io/fabric8/maven/docker/StopMojo.java
Fixed: stop containers based on naming strategy (should stop all containers based on alias if naming strategy is used)
Fixed: catch exception if container alias does not exists (previously it would throw exception now it just displays a warning)
Fixed: docker.allContainers, docker.sledgeHammer can be set from maven properties now (before only from system properties).
> Fixes for stop mojo

- src/main/java/io/fabric8/maven/docker/StartMojo.java
- src/main/java/io/fabric8/maven/docker/config/WaitConfiguration.java
- src/main/java/io/fabric8/maven/docker/util/WaitUtil.java
Signed-off-by: Zoltan Ersek <zoltan.ersek@hpe.com>
> Add flag to ignore certificates when waiting for https ping. 

- src/main/java/io/fabric8/maven/docker/AbstractBuildSupportMojo.java
- src/main/java/io/fabric8/maven/docker/assembly/DockerAssemblyManager.java
Since version 1.5.0, Docker interprets the Dockerfile instruction `FROM scratch` as a special case indicating a no-base image.
This implies that there is no more an image named 'scratch'.
Building an image from a Dockerfile with `FROM scratch` currently
causes the error:
`Unable to pull 'scratch:latest': 'scratch' is a reserved name (Internal Server Error: 500)`
Avoid auto-pulling 'scratch' image.
> Avoid auto-pulling 'scratch' image

- src/main/java/io/fabric8/maven/docker/service/BuildService.java
When building an image, the log messages are slightly confusing:
> [INFO] DOCKER> [mydata] "data": Built image sha256:04512
> [INFO] DOCKER> [mydata] "data": Removed image 
This sounds like the image gets deleted immediately after being built. In fact, it's only the previous version that is deleted.
With this change, the message is now
> [INFO] DOCKER> [mydata] "data": Removed old image sha256:e0bea
> Clarify log message when removing old image

- src/main/asciidoc/inc/build/_assembly.adoc
- src/main/java/io/fabric8/maven/docker/assembly/DockerAssemblyConfigurationSource.java
- src/main/java/io/fabric8/maven/docker/config/AssemblyConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/ConfigKey.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
> Lots of warnings are displayed when assembly.mode is tar or tgz when building on windows

- src/main/java/io/fabric8/maven/docker/config/WaitConfiguration.java
The status parameter in the `HttpConfiguration` constructor is ignored and results in a null status. This is not a problem when using an XML config such as below, because the fields are injected differently. 
```xml
<wait>
<http>
<url>http://localhost/status</url>
<method>GET</method>
<status>200</status>
</http>
</wait>
```
Found this out when writing an `ExternalConfigHandler` which uses code to construct the `WaitConfiguration` object.
> Fixes bug where status was not being set on HttpConfiguration

- src/main/java/io/fabric8/maven/docker/assembly/DockerFileBuilder.java
- src/test/java/io/fabric8/maven/docker/assembly/DockerFileBuilderTest.java
- src/test/resources/docker/Dockerfile_tcp.test
- src/test/resources/docker/Dockerfile_udp.test
Hi @rhuss, sorry for the confusion, I've been out awhile with pneumonia.  Finally got back to this, and my branch was far enough behind (and I apologize I'm kind of a Git newb) I thought it would be easier to apply to a fresh fork.  
Your original link for committing guidelines doesn't work anymore, so I don't think I got everything right, other than correcting the author on the commit.  Let me know if I need to do anything else.
> Removed restriction that port mappings are integers to support UDP

- src/main/asciidoc/inc/push/_overview.adoc
The global option 'image' was renamed to 'filter' but the push section referenced the old name.
Signed-off-by: Tamsin Slinn <tam.slinn@gmail.com>
> Corrected reference to global option 'filter'

- src/main/java/io/fabric8/maven/docker/config/WaitConfiguration.java
- src/main/java/io/fabric8/maven/docker/util/WaitUtil.java
- src/test/java/io/fabric8/maven/docker/util/WaitUtilTest.java
The log message when waiting on a URL with default settings is a bit confusing:
```
Waiting on url http://localhost:33068/foo/ with method null for status null
```
WIth this change, the message now includes the default HTTP method and the default
status code range:
```
Waiting on url http://localhost:33068/foo/ with method HEAD for status 200..399
```
> Clarify log message when waiting for URL

- doc/changelog.md
- pom.xml
- src/main/java/io/fabric8/maven/docker/access/hc/unix/UnixConnectionSocketFactory.java
- src/main/java/io/fabric8/maven/docker/access/hc/unix/UnixSocket.java
7afec26aaaa9ebe39065a8daa8a96db42945a22e
> Revert "Upgrade to jnr-unixsocket 0.15"

- src/main/java/io/fabric8/maven/docker/access/UrlBuilder.java
- src/test/java/io/fabric8/maven/docker/UrlBuilderTest.java
This is required to make unit tests predictable.
> Fix order of query parameters in the API

- src/main/java/io/fabric8/maven/docker/util/EnvUtil.java
- src/test/java/io/fabric8/maven/docker/util/EnvUtilTest.java
When configuration has an empty link, a NullPointerException is thrown.
```xml
<configuration>
<links>
<link></link>
</links>
...
</configuration>
```
> fix empty link causing NullPointerException

- pom.xml
- src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
- src/test/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandlerTest.java
Allow users to source the run commands from properties.
Signed-off-by: Steve Newson <Steven.Newson@gmail.com>
> Fix handling of Run Commands from properties.

- doc/changelog.md
- src/main/asciidoc/inc/external/_property_configuration.adoc
- src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java
- src/main/java/io/fabric8/maven/docker/StartMojo.java
- src/main/java/io/fabric8/maven/docker/access/DockerAccessException.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
- src/test/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandlerTest.java
Otherwise no build configuration will be created. This fixes #736.
Also made error messages a bit more verbose.
> Enable properties build only when `from` or `fromExt` is set

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/service/RegistryService.java
- src/main/java/io/fabric8/maven/docker/util/AuthConfigFactory.java
Especially when there is no auth set, don't barf but simply don't
use any auth.
Fixes #731
> Be more robust when parsing Docker auth config

- doc/changelog.md
- samples/data-jolokia/pom.xml
- src/main/asciidoc/inc/build/_assembly.adoc
- src/main/asciidoc/inc/build/_overview.adoc
- src/main/java/io/fabric8/maven/docker/assembly/AssemblyFiles.java
- src/main/java/io/fabric8/maven/docker/assembly/DockerAssemblyManager.java
- src/main/java/io/fabric8/maven/docker/assembly/DockerFileBuilder.java
- src/main/java/io/fabric8/maven/docker/assembly/MappingTrackArchiver.java
- src/main/java/io/fabric8/maven/docker/config/AssemblyConfiguration.java
- src/test/java/io/fabric8/maven/docker/assembly/MappingTrackArchiverTest.java
this can be used to specify the assembly name which is used also as directory
for holding the assembly files. I.e. the directory which needs to be refered to when
an extrean Dockerfile wants to include an assembly. "targetDir" now defaults to "/" + this name.
Also extended the documentation to clarify the usage.
Fixes #634
> Add new assembly option "name"

- README.md
- src/main/asciidoc/inc/_goals.adoc
This PR adds to the documentation the default bindings of the plugin goals to the Maven lifecycle phases.
I hope this helps folks to better grasp _when_ the plugin does _what_ and reduce the "I have no idea why this happens" moments for newbies (like me).
> Document default lifecycle bindings

- src/main/java/io/fabric8/maven/docker/service/DockerAccessFactory.java
Fix skipDockerMachine when a docker machine configuration is provided.
Fixes #759
> Fix skipDockerMachine

- src/main/java/io/fabric8/maven/docker/assembly/DockerAssemblyManager.java
Currently the Dockerfile interpolation doesn't include properties specified from
the command line, and only uses the values in the POM.  This change allows
the cli to set new properties and override the pom property values.
> Allow system/cli properties to be used in the Dockerfile

- src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
- src/test/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandlerTest.java
PropertyConfigHandler#buildConfigured should also return true if the dockerFile or dockerFileDir properties are set
BuildImageConfiguration do not overwrite filter and cleanup default values with null properties
Signed-off-by: Adrian Gonzalez <adrian.gonzalez@ef.com>
> PropertyConfigHandler fixes

- samples/custom-net/pom.xml
- src/main/asciidoc/inc/start/_depends-on.adoc
- src/main/java/io/fabric8/maven/docker/config/ImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/RunImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/util/EnvUtil.java
Allow comma separated list of <dependsOn> elements.  (Similar to #558)
* Feature request: Allow something like:
```
<dependsOn>
<container>mongo,identity</container>
</dependsOn>
```
> Allow comma separated list of container names in dependsOn elements

- doc/changelog.md
- src/main/asciidoc/inc/build/_configuration.adoc
- src/main/asciidoc/inc/start/_port-mapping.adoc
- src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/RunImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/util/EnvUtil.java
- src/test/java/io/fabric8/maven/docker/util/EnvUtilTest.java
Allow empty list elements.  This often occurs when a parent (corporate) pom has configuration values that are overridden by some, but not all, children.
> Ignore empty List<String> configuration values

- src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/util/DockerFileUtil.java
- src/main/java/io/fabric8/maven/docker/util/EnvUtil.java
- src/test/java/io/fabric8/maven/docker/util/EnvUtilTest.java
Fix test failures when build under Windows.
The validation of the Windows filename is copied from stackoverflow: https://stackoverflow.com/a/6804755
> Fix test failures when build under Windows

- src/main/java/io/fabric8/maven/docker/assembly/AllFilesExecCustomizer.java
- src/main/java/io/fabric8/maven/docker/assembly/ArchiverCustomizer.java
- src/main/java/io/fabric8/maven/docker/assembly/DockerAssemblyManager.java
- src/main/java/io/fabric8/maven/docker/service/ArchiveService.java
This will expose the archive customizer to be able to write to the root of the generated tar file (assembly config allows to write into a subfolder, e.g. "maven" by default). S2I files should be written to the ".s2i" folder in the root of the archive.
@rhuss I've tried not to expose maven/plexus objects but I can't find a straightforward approach.
This is to fix the Issue: https://github.com/fabric8io/fabric8-maven-plugin/issues/1009
Related change to f-m-p: https://github.com/nicolaferraro/fabric8-maven-plugin/tree/1009-java-options
> Adding customizer to service to allow changing the archive root

- src/main/java/io/fabric8/maven/docker/config/handler/compose/DockerComposeConfigHandler.java
> Docker Compose: allow version "2" not only "2.x"

- src/main/asciidoc/inc/_authentication.adoc
- src/main/java/io/fabric8/maven/docker/access/AuthConfig.java
- src/main/java/io/fabric8/maven/docker/access/ecr/AwsSigner4.java
- src/test/java/io/fabric8/maven/docker/access/ecr/AwsSigner4RequestTest.java
In order to use temporary security credentials provided by the AWS
Security Token Service (AWS STS) to sign requests, the session token has
to be included.
> Extended Authentication: allow usage of temporary security credentials

- doc/changelog.md
- src/main/asciidoc/inc/_authentication.adoc
- src/main/java/io/fabric8/maven/docker/access/util/ExternalCommand.java
- src/main/java/io/fabric8/maven/docker/util/AuthConfigFactory.java
- src/main/java/io/fabric8/maven/docker/util/CredentialHelperClient.java
- src/test/java/io/fabric8/maven/docker/util/AuthConfigFactoryTest.java
Signed-off-by: Denis N. Antonioli <d_n_antonioli@yahoo.com>
Fix issue #806.
In need of feedback, especially any idea on how to test this…
I have only performed happy-path tests manually until now.
> use credential helper if defined

- src/main/java/io/fabric8/maven/docker/access/log/LogRequestor.java
- src/test/java/io/fabric8/maven/docker/access/log/LogRequestorTest.java
Changes the log line match pattern to preserve leading whitespace in log
lines by only consuming a single space delimiter between the timestamp
and the message body.
Signed-off-by: Scott Coplin <coplin.6@osu.edu>
> Preserve leading whitespace in logs

- doc/changelog.md
- src/main/asciidoc/inc/build/_overview.adoc
- src/main/java/io/fabric8/maven/docker/assembly/DockerAssemblyManager.java
- src/main/java/io/fabric8/maven/docker/service/BuildService.java
- src/main/java/io/fabric8/maven/docker/util/DockerFileUtil.java
- src/test/java/io/fabric8/maven/docker/util/DockerFileUtilTest.java
- src/test/resources/interpolate/at/Dockerfile_1
- src/test/resources/interpolate/at/Dockerfile_1.expected
- src/test/resources/interpolate/var/Dockerfile_1
- src/test/resources/interpolate/var/Dockerfile_1.expected
Replaces the regex-based property interpolation with the plexus classes
used typically by maven to perform interpolation.  This allows
references to things like ${project.build.directory} in the Dockerfile.
[fixes #871]
Signed-off-by: Scott Coplin <coplin.6@osu.edu>
> Support standard maven property interpolation

- doc/changelog.md
- samples/data-jolokia/pom.xml
- src/main/asciidoc/inc/start/_logging.adoc
- src/main/java/io/fabric8/maven/docker/log/DefaultLogCallback.java
- src/main/java/io/fabric8/maven/docker/log/LogOutputSpec.java
- src/main/java/io/fabric8/maven/docker/log/LogOutputSpecFactory.java
- src/main/java/io/fabric8/maven/docker/util/FormatParameterReplacer.java
- src/main/java/io/fabric8/maven/docker/util/ImageNameFormatter.java
- src/test/java/io/fabric8/maven/docker/log/DefaultLogCallbackTest.java
- src/test/java/io/fabric8/maven/docker/log/LogOutputSpecFactoryTest.java
This replaces #876 as its a bit more flexible and does not require a new configuration option.
You can use now a prefix `%z` for an empty string
> feature: Use log prefix as format

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/assembly/DockerAssemblyManager.java
- src/test/java/io/fabric8/maven/docker/assembly/DockerAssemblyManagerTest.java
- src/test/resources/docker/Dockerfile_assembly_verify_copy_chown_valid.test
- src/test/resources/docker/Dockerfile_assembly_verify_copy_invalid.test
- src/test/resources/docker/Dockerfile_assembly_verify_copy_valid.test
This fixes logging an invalid warning that results when providing the new `--chown` flag to the `COPY` command in a custom Dockerfile.
> Fix warning that results when providing new --chown COPY flag

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/access/DockerAccess.java
- src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java
- src/main/java/io/fabric8/maven/docker/service/VolumeService.java
This fix is admittedly simplistic.  It does not take into account any of the other possible causes for an exception.  However, if you are using volume-clean, chances are you're using volume-create, or many of the other goals provided by DMP.  In that case, you will almost certainly receive errors pointing you at the
real problem.
> Don't fail build if volume-clean fails.

- src/main/java/io/fabric8/maven/docker/access/ecr/EcrExtendedAuth.java
This allows using Extended Authentication behind a proxy, as it advices
the HttpClient to use the JVM's standard system properties for
proxies (https://docs.oracle.com/javase/6/docs/technotes/guides/net/proxies.html).
> [Extended Authentication] Enable usage of system properties for HttpClient 

- src/main/java/io/fabric8/maven/docker/StartMojo.java
Moves the shutdown hook in the StartMojo earlier so that containers that
will be cleaned up even if they haven't been fully started per their
wait conditions.  This is especially likely to occur on aborted builds.
[fixes #921]
Signed-off-by: Scott Coplin <coplin.6@osu.edu>
> More reliably clean up failed/aborted containers

- src/main/asciidoc/inc/build/_configuration.adoc
The element is named [args](https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java#L107), not buildArgs in the image configuration. Took me a while to figure that out.
> Fix the name of buildArgs -> args inside the documentation

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/access/log/LogRequestor.java
- src/main/java/io/fabric8/maven/docker/wait/LogMatchCallback.java
- src/main/java/io/fabric8/maven/docker/wait/LogWaitChecker.java
- src/main/java/io/fabric8/maven/docker/wait/LogWaitCheckerCallback.java
- src/test/java/io/fabric8/maven/docker/access/log/LogRequestorTest.java
- src/test/java/io/fabric8/maven/docker/wait/ExitCodeCheckerTest.java
- src/test/java/io/fabric8/maven/docker/wait/LogMatchCallbackTest.java
- src/test/java/io/fabric8/maven/docker/wait/LogWaitCheckerTest.java
Fixed entity stream closing
Added callback mechanism to signal wait lock condition to main thread including tests
Changed mocked DockerAccess dependency including expectations in LogWaitChecker tests
> #862 - Fix for hanging wait on log

- src/main/java/io/fabric8/maven/docker/util/CredentialHelperClient.java
Don't throw an exception if the credentials helper doesn't return a version string
Fixes #896
Signed-off-by: Giuseppe Iannello <giuseppe.iannello@brokenloop.net>
> Credentials helper version string fix

- src/main/java/io/fabric8/maven/docker/config/NetworkConfig.java
If property based configuration was used, and network mode was set to custom, `aliases` is by default set to null if no aliases are specified, causing NPE.
Example:
```
<properties>
....
<docker.network.mode>custom</docker.network.mode>
<docker.network.name>some-net</docker.network.name>
</properties>
```
```
mvn docker:build -e
...
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.23.0:run (default-cli) on project xxxxx: Execution default-cli of goal io.fabric8:docker-maven-plugin:0.23.0:run failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:docker-maven-plugin:0.23.0:run (default-cli) on project xxxx: Execution default-cli of goal io.fabric8:docker-maven-plugin:0.23.0:run failed.
at …
```
> Fix NPE in network config

- src/main/java/io/fabric8/maven/docker/log/DefaultLogCallback.java
- src/main/java/io/fabric8/maven/docker/log/SharedPrintStream.java
- src/test/java/io/fabric8/maven/docker/log/DefaultLogCallbackTest.java
Attempt to fix #911 
Root cause: `${project.build.directory}` (`target/`) doesn't exist and because of this an exception is thrown when attempting to create the SharedPrintStream to `target/postgres.log`; the catch block tries to log to this SharedPrintStream which wasn't constructed
Solution: create the dirs leading to the log file before opening the stream
> #911 Fix NPE in LogCallback

- doc/changelog.md
- samples/simple-configuration/pom.xml
- samples/simple-configuration/src/main/docker/Dockerfile
- src/main/asciidoc/inc/_image-configuration.adoc
- src/main/asciidoc/inc/image/_simple_configuration_example.adoc
- src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java
- src/main/java/io/fabric8/maven/docker/BuildMojo.java
- src/main/java/io/fabric8/maven/docker/config/ImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/util/DockerFileUtil.java
When only a single image is build with Dockerfile, no need to provide
too much parameters in configuration; build ImageConfiguration dynamically
with the given defaults.
#957
> Fixes #957 Simplify configuration

- samples/properties/pom.xml
- src/main/asciidoc/inc/build/_buildargs.adoc
- src/main/asciidoc/inc/external/_property_configuration.adoc
- src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java
- src/main/java/io/fabric8/maven/docker/config/AssemblyConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/ConfigHelper.java
- src/main/java/io/fabric8/maven/docker/config/ImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/NetworkConfig.java
- src/main/java/io/fabric8/maven/docker/config/RunImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/UlimitConfig.java
- src/main/java/io/fabric8/maven/docker/config/WaitConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/WatchImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/handler/ImageConfigResolver.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/ConfigKey.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyMode.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/ValueCombinePolicy.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/ValueProvider.java
- src/main/java/io/fabric8/maven/docker/service/ContainerTracker.java
- src/main/java/io/fabric8/maven/docker/service/WaitService.java
- src/main/java/io/fabric8/maven/docker/util/EnvUtil.java
- src/test/java/io/fabric8/maven/docker/config/ConfigHelperTest.java
- src/test/java/io/fabric8/maven/docker/config/ImageConfigResolverTest.java
- src/test/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandlerTest.java
- src/test/java/io/fabric8/maven/docker/config/handler/property/PropertyModeTest.java
- src/test/java/io/fabric8/maven/docker/config/handler/property/ValueProviderTest.java
- src/test/java/io/fabric8/maven/docker/util/EnvUtilTest.java
(originally discussed in #938. Branch based on commit in #941 with run/buildEnv)
This adds supports to use both Properties based configuration and POM based configuration to configure the same image. This is done by adding the `source` configuration to the `<external>` section, which can have one of the following values:
* `properties` - default, same as existing properties based configuration (ie. no merge)
* `pom, properties` - merge pom configs and properties, with values in POM having priority
* `properties, pom` - merge pom configs and properties, with values in properties having priority
* (`pom` - pretty useless, same as not having <external> at all)
Can also be enabled by pure properties (only makes sense for single image), by setting the property …
> Merging Properties and POM based configuration

- src/main/asciidoc/inc/_implicit-properties.adoc
- src/main/asciidoc/index.adoc
- src/main/java/io/fabric8/maven/docker/access/ContainerCreateConfig.java
- src/test/java/io/fabric8/maven/docker/access/ContainerCreateConfigTest.java
Fixes #960 
Somehow these ${...} parameters are not being picked up by maven
properly when used solely without any suffix string literal, the maven
parameter string comes off as NULL. So adding a workaround for this.
We'll use +${...} as a parameter which would be handled by dmp afterwards
> Fixes #960 Property placeholders are not interpolated when they are only thing in XML

- src/main/java/io/fabric8/maven/docker/access/log/LogRequestor.java
This fixes a regression introduced in the 0.24.0 version of the plugin.
I have a small test program to demonstrate the problem below.
Normally, Apache HTTP Client will drain an http request upon closing the input stream.
In this case we consume the docker logs in 'follow' mode which will cause the docker daemon to never close the connection on its end.
Thus the http client `close()` call will block forever.
The main thread is responsible for calling `request.abort()`, which will signal Apache HTTP Client to close the socket on it's end and thus the `close()` call can unblock.
Due to the refactoring in 0.24.0, there is a deadlock on this object in LogRequestor.java
```
// Lock for synchronizing closing of requests
private final Object lock = new Object();
```
Since the log requestor thread …
> Fix deadlock waiting on docker log pattern to match

- doc/changelog.md
- src/main/asciidoc/inc/_docker-remove.adoc
- src/main/asciidoc/inc/_global-configuration.adoc
- src/main/asciidoc/inc/build/_configuration.adoc
- src/main/asciidoc/inc/push/_configuration.adoc
- src/main/java/io/fabric8/maven/docker/BuildMojo.java
- src/main/java/io/fabric8/maven/docker/PushMojo.java
- src/main/java/io/fabric8/maven/docker/RemoveMojo.java
- src/main/java/io/fabric8/maven/docker/service/RegistryService.java
When pushing and removing images, the docker.skip.tag property is not
used and can cause errors because the plugin will try to push and/or
remove image tags that don't exist because they were skipped during the
build process.
https://github.com/fabric8io/docker-maven-plugin/issues/869
Fix bug in removing tagged images
Code to remove tagged images was not creating the image name correctly
Signed-off-by: Mark Whelan <mbwhelan@gmail.com>
> Use docker.skip.tag property on push and remove

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/StartMojo.java
- src/main/java/io/fabric8/maven/docker/config/LogConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
- src/test/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandlerTest.java
Follow-up on #948, bugfix. LogConfiguration was always created with enabled=true, even if no log properties where set.
Desired functionality: if any config or property in LogConfiguration is set, enabled shall be true.
Also added short note to changelog.
> Unbreak merge of LogConfiguration config 

- src/main/java/io/fabric8/maven/docker/assembly/DockerFileBuilder.java
- src/test/java/io/fabric8/maven/docker/assembly/DockerFileBuilderTest.java
- src/test/resources/docker/Dockerfile.multiline_label.test
<labels> section should be able to support multiline labels and empty labels
> support multiline labels and empty labels

- src/main/java/io/fabric8/maven/docker/util/CredentialHelperClient.java
As there is currently no other need for multi line handling for the `ExternalCommand` abstraction I just implemented the naive approach of collecting the lines and joining them in the end.
> Fix #930: Handle multi line credential helper responses

- src/main/java/io/fabric8/maven/docker/SaveMojo.java
docker:save will now also create the target directory when a saveFile has been
configured explicitly. Before this was only the case when the target
(directory) as computed automatically.
Signed-off-by: Thomas Weißschuh <thomas.weissschuh@de.amadeus.com>
> [SaveMojo] create the savedir for explictl targets

- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
- src/test/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandlerTest.java
The POM provided configuration was totally ignored since getDockerFile() was null (should use Raw instead)
Bug in #948, only affects those trying to use config + properties. Temporary workaround is to set property `docker.dockerFile` and build goal will start working again.
> Unbreak use of build/dockerFile in properties mode

- src/main/asciidoc/inc/_global-configuration.adoc
- src/main/java/io/fabric8/maven/docker/access/DockerMachine.java
- src/main/java/io/fabric8/maven/docker/config/DockerMachineConfiguration.java
- src/main/java/io/fabric8/maven/docker/service/DockerAccessFactory.java
- src/test/java/integration/DockerAccessIT.java
- src/test/java/integration/DockerMachineIT.java
If using Docker Machine with the AWS EC2 driver, the remote host will have a new IP address every time it is started up again.  This causes the Docker Maven plug-in to fail with an error about certificates being invalid when starting up the machine automatically.  Add an option to automatically regenerate the certificates for the new IP address after startup.  Setting this option to true will allow Docker Machines running in AWS EC2 to be automatically started up into a usable state by the Docker Maven plug-in. (Without this option, such automatically started machines will fail the Maven Docker plug-in invocation complaining about certificates being invalid as the existing certificates are associated with the old IP address)
The changes have been tested with the option both on and off, …
> Add option for regenerating certificates after starting Docker Machine

- samples/healthcheck/pom.xml
- src/main/asciidoc/inc/build/_healthcheck.adoc
- src/main/asciidoc/inc/external/_property_configuration.adoc
- src/main/java/io/fabric8/maven/docker/assembly/DockerFileBuilder.java
- src/main/java/io/fabric8/maven/docker/assembly/DockerFileOption.java
- src/main/java/io/fabric8/maven/docker/config/HealthCheckConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/ConfigKey.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
- src/test/java/io/fabric8/maven/docker/assembly/DockerFileBuilderTest.java
- src/test/java/io/fabric8/maven/docker/config/HealthCheckConfigTest.java
Addresses issue #961.  A startPeriod may now be specified in the health
check in the POM.  This works in the same way as adding a start-period
option to a Dockerfile.
> Add startPeriod to healthCheck

- src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/HealthCheckConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/RunImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/ValueProvider.java
- src/test/java/io/fabric8/maven/docker/assembly/DockerFileBuilderTest.java
- src/test/java/io/fabric8/maven/docker/config/HealthCheckConfigTest.java
- src/test/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandlerTest.java
- src/test/java/io/fabric8/maven/docker/service/RunServiceTest.java
Any `<entrypoint><exec><arg>...</arg>` would disappear when any property mode was enabled (but corresponding property not defined as property), due to bad string conversion.
Fix is to get rid of all string conversions dealing with Arguments (which was mostly from test).
Bug in #948
> Unbreak setting of entrypoint in exec form when property mode is enabled

- src/main/asciidoc/inc/external/_property_configuration.adoc
- src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java
- src/main/java/io/fabric8/maven/docker/config/ConfigHelper.java
- src/main/java/io/fabric8/maven/docker/config/UlimitConfig.java
- src/main/java/io/fabric8/maven/docker/config/handler/ImageConfigResolver.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyMode.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/ValueProvider.java
- src/test/java/io/fabric8/maven/docker/config/ConfigHelperTest.java
- src/test/java/io/fabric8/maven/docker/config/ImageConfigResolverTest.java
- src/test/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandlerTest.java
By default it works as previous, but if explicit <external> is added to each image, and i.e. setting a custom prefix, it work.
This is useful when i.e. env has `docker.imagePropertyConfiguration` set globally (i.e. settings.xml), and a Maven project happens to have multiple images.
Also add support for docker.imagePropertyConfiguration=skip, for i.e. overriding parents config and disable it (note that setting this in pom <properties> will not override a value in settings.xml, mostly useful to override parent pom).
> Add possiblity to use docker.imagePropertyConfiguration with multipe images

- .gitignore
- src/main/java/io/fabric8/maven/docker/config/handler/compose/DockerComposeServiceWrapper.java
- src/test/java/io/fabric8/maven/docker/config/handler/compose/DockerComposeConfigHandlerTest.java
- src/test/resources/compose/docker-compose-network-aliases.yml
Hi all,
I had some problems to start an external docker-compose.yml because of network aliases configuration mismatch. 
The DockerComposeServiceWrapper does not manage correctly the network name nor the aliases.
There is a unit test, the changes and a docker-compose file to check the behaviour.
Regards Gianluca.
```
version: '2.2'
services:
service1:
image: image
networks:
network1:
aliases:
- alias1
- alias2
service2:
image: image
networks:
- network1
service3:
image: image
networks:
network1:
aliases:
- alias1
```
> Network aliases management

- src/main/asciidoc/inc/_authentication.adoc
Maybe it's just that I'm an ECR noob, coming from GCR background. I found it quite difficult to figure out what is the proper registry value.
What you do for ECR is quite different from the OS example: `-Ddocker.registry=docker-registry.domain.com:80/default/myimage`
> Clarify how to set docker.registry for ECR

- src/main/java/io/fabric8/maven/docker/access/AuthConfig.java
- src/test/java/io/fabric8/maven/docker/util/AuthConfigTest.java
I was getting mysterious failures when pushing images -- turned out I had some characters in the password causing `+` to be part of the resulting base64 string.
It appears that this isn't documented very well, but Docker Engine requires URL-safe base64 encoding.
Related issue: https://github.com/moby/moby/issues/19214
Related code: https://github.com/moby/moby/blob/4bf8714fac11e95e835cf78eb15ba5a518c67c4b/api/server/router/image/image_routes.go#L140-L146
With this fix, my arcane password is now working.
> Fix encoding for X-Registry-Auth

- src/main/java/io/fabric8/maven/docker/StartMojo.java
We should finally switch to Optionals, now that we are on Java 8
Fixes #1091
> fix: Check for null before accessing volume configuration

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/access/UrlBuilder.java
- src/main/java/io/fabric8/maven/docker/util/ImageName.java
- src/test/java/io/fabric8/maven/docker/util/ImageNameTest.java
> Fix #541: Allow @sha256 digest for tags in FROM

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java
- src/main/java/io/fabric8/maven/docker/service/DockerAccessFactory.java
- src/test/java/integration/DockerAccessIT.java
- src/test/java/integration/DockerAccessWinIT.java
- src/test/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClientTest.java
#1060 Send a test request to the Daemon, and check whether it succeeds. In the return response
there's a header Api-Version: which holds the actual Docker daemon version. If this test
request because of a too low version, we can just pick up that version and use it as
minimal version for us.
> Fix #1060: Smarter API version handling

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java
Since Api-Version header was introduced in 1.25, we should send a minimal api-version
rather than just sending null. See this comment:
https://github.com/fabric8io/docker-maven-plugin/issues/1060#issuecomment-453348656
> Reintroduce minimal api-version parameter for Api-Versions < 1.25

- doc/changelog.md
- src/main/asciidoc/inc/image/_naming.adoc
The same document claims the default pattern is `%n-%i` and `%n-%a` in different places.
It seems to me it's `%n-%i`
> docs: Correct default image naming

- doc/changelog.md
- pom.xml
Resolves issues similar to #1119.
> Update jnr-unixsocket 0.21->0.22.

- src/main/asciidoc/inc/start/_configuration.adoc
- src/main/java/io/fabric8/maven/docker/access/ContainerHostConfig.java
- src/main/java/io/fabric8/maven/docker/config/RunImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/ConfigKey.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
- src/main/java/io/fabric8/maven/docker/service/RunService.java
- src/test/java/io/fabric8/maven/docker/access/ContainerHostConfigTest.java
- src/test/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandlerTest.java
- src/test/java/io/fabric8/maven/docker/service/RunServiceTest.java
- src/test/resources/docker/containerCreateConfigAll.json
- src/test/resources/docker/containerHostConfigAll.json
Added 'autoRemove' option to run configuration to automatically remove a container when it exits (like docker run --rm).
This is needed to make sure that a container will be removed after exit even if the maven process is killed before it could stop the container.
> Added 'autoRemove' option

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/util/ImageName.java
- src/test/java/io/fabric8/maven/docker/util/ImageNameTest.java
ImageName.java and respective test class adjusted to be able to handle
image names with tag AND sha256 digest like:
image_name:image_tag@sha256<digest>
Signed-off-by: Marcus Konrad <M.M.Konrad@web.de>
> Enhance Fix #541: Allow @sha256 digest for tags in FROM

- doc/changelog.md
- src/main/asciidoc/inc/_authentication.adoc
- src/main/java/io/fabric8/maven/docker/access/ecr/EcrExtendedAuth.java
- src/main/java/io/fabric8/maven/docker/util/AuthConfigFactory.java
This PR adds support for EC2 instance roles as described in issue #1177.
I didn't add any tests since they would only work when run on a correctly configured EC2 instance.
> Implemented authentication via EC2 instance role for ECR

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/SaveMojo.java
- src/test/java/io/fabric8/maven/docker/SaveMojoTest.java
Followup and refactoring of #1194 // @wrosenuance
> Prevent docker:save failing when no images are defined.

- src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/util/EnvUtil.java
- src/test/java/io/fabric8/maven/docker/config/BuildImageConfigurationTest.java
- src/test/java/io/fabric8/maven/docker/util/EnvUtilTest.java
The Windows file name validations were inconsistent with other platform
behaviour and impede the creation of cross-platform POMs.
> Issue #1195 Remove Windows file name validations.

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java
- src/main/java/io/fabric8/maven/docker/util/AnsiLogger.java
- src/main/java/io/fabric8/maven/docker/util/EnvUtil.java
- src/test/java/io/fabric8/maven/docker/util/AnsiLoggerTest.java
Fix for #1108.
If the plugin is set to disable color output, or detects pre-3.5.0 Maven
on Windows, ANSI color logging is disabled. Previously this would then
disable color logging for all subsequent plugins, but now the setting is
restored. Additionally it has been enabled for Windows with Maven 3.5.0+.
> Issue #1108 Restore color log output after plugin executes.

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/SaveMojo.java
Fixes NPE that happens if you run mvn docker:save -Dfile=no-directory-name.tar
> Issue #1203 NPE if docker:save called with filename only.

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/SaveMojo.java
- src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java
- src/main/java/io/fabric8/maven/docker/config/ArchiveCompression.java
Change the default compression level to 3 in line with [JDK-8142920](https://bugs.openjdk.java.net/browse/JDK-8142920) and increase buffer sizes for copy and compression.
> Issue #1205 Increase GZIP compression speed for docker:save.

- doc/changelog.md
- src/main/asciidoc/inc/build/_configuration.adoc
- src/main/asciidoc/inc/build/_overview.adoc
- src/main/asciidoc/inc/external/_property_configuration.adoc
- src/main/asciidoc/index.adoc
- src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java
- src/main/java/io/fabric8/maven/docker/config/ArchiveCompression.java
- src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/ConfigKey.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
- src/main/java/io/fabric8/maven/docker/model/ImageArchiveManifest.java
- src/main/java/io/fabric8/maven/docker/model/ImageArchiveManifestAdapter.java
- src/main/java/io/fabric8/maven/docker/model/ImageArchiveManifestEntry.java
- src/main/java/io/fabric8/maven/docker/model/ImageArchiveManifestEntryAdapter.java
- src/main/java/io/fabric8/maven/docker/service/BuildService.java
- src/main/java/io/fabric8/maven/docker/util/ImageArchiveUtil.java
- src/main/java/io/fabric8/maven/docker/util/NamePatternUtil.java
- src/test/java/io/fabric8/maven/docker/model/ImageArchiveManifestAdapterTest.java
- src/test/java/io/fabric8/maven/docker/model/ImageArchiveManifestEntryAdapterTest.java
- src/test/java/io/fabric8/maven/docker/util/ImageArchiveUtilTest.java
- src/test/java/io/fabric8/maven/docker/util/NamePatternUtilTest.java
This is a work-in-progress to address #1207, which has the motivation for this PR. I'm opening a PR early to get feedback on the proposal and initial implementation before finalising and updating the documentation.
Adding ``<loadNamePattern>my-company/my-image:*</loadNamePattern>`` to a ``<build>`` section that specifies a ``<dockerArchive>`` will cause the build mojo to read the archive before sending it to the Docker server and to find the manifest.json that describes the contents. Then it will try to parse the JSON, figure out the different images within the archive (there can be several) and their associated tags (also may be multiple per image), and from there will attempt to match the pattern against repo tags, stopping with the first image it finds.
Having found a match, the mojo …
> Find the name of an image in an archive using a pattern

- doc/changelog.md
- src/main/asciidoc/inc/_docker-save.adoc
- src/main/java/io/fabric8/maven/docker/SaveMojo.java
- src/test/java/io/fabric8/maven/docker/SaveMojoTest.java
This PR is to add the ability to attach an image archive produced by docker:save to the project as an artifact. Currently this is not possible and archives have to be attached using something like build-helper-maven-plugin.
To avoid conflict with docker:source, the default attach classifier is `archive` (or `archive-<saveAlias>`), instead of `docker` (or `docker-<alias>`) as used by that mojo.
> Add the ability to attach a saved image archive as a project artifact

- doc/changelog.md
- src/main/asciidoc/inc/build/_configuration.adoc
- src/main/java/io/fabric8/maven/docker/access/BuildOptions.java
- src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/ConfigKey.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
- src/main/java/io/fabric8/maven/docker/service/BuildService.java
- src/test/java/io/fabric8/maven/docker/access/BuildConfigTest.java
- src/test/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandlerTest.java
Fixes #1132 :This is my initial attempt. I'm not sure how to test it so this effort is incomplete. This PR relates to issue
> Added support for 'cachefrom' when building an image

- doc/changelog.md
- src/test/java/io/fabric8/maven/docker/config/BuildImageConfigurationWithMavenDepsTest.java
The absolute file paths in the test case need to be adjusted to the platform.
> Fix for issue #1220.

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/StartMojo.java
Fix #1112 
port mappings should be written after we start containers.
Tested on https://github.com/r0haaaan/dmp-demo-project project with and without this patch. With this patch, I was able to see ports.properties file getting generated:
```
~/work/repos/dmp-demo-project : $ mvn docker:start
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< io.fabric8:dockerfile >------------------------
[INFO] Building dmp-sample-dockerfile 0.30-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- docker-maven-plugin:0.30-SNAPSHOT:start (default-cli) @ dockerfile ---
[INFO] DOCKER> [test-db:latest] "dockerfile": Start container 32772f1b0130
[INFO] DOCKER> [test-db:latest] "dockerfile": Pausing for 5000 ms
[INFO] …
```
> Fix #1112: portPropertyFile not written anymore

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/access/AuthConfig.java
- src/main/java/io/fabric8/maven/docker/util/AuthConfigFactory.java
This PR fixes #1249 by checking for the identity token and using it if found in the Docker config.json.
Using this I am able to access Azure Container Registries using the credential token created by running `az acr login`.
> Use identity token from Docker config if present

- src/main/java/io/fabric8/maven/docker/util/AuthConfigFactory.java
- src/test/java/io/fabric8/maven/docker/util/AuthConfigFactoryTest.java
A quick PR to address issue found here:
https://github.com/fabric8io/docker-maven-plugin/issues/1262
Add a null check and refactor tests to accommodate serialisation of nulls when auth config file created.
> Add null check for null instance in config.json for email

- src/main/java/io/fabric8/maven/docker/service/WaitService.java
This is a fix for https://github.com/fabric8io/docker-maven-plugin/issues/1234
If the network mode is not specified, the networkMode string is "default". Although it is technically bridge mode, this if block doesn't think it is, so it fails to get the host.
> Wait service should treat default network mode same as bridge (#1234)

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/service/WaitService.java
It seems there is a regression on healthy option since 0.25.0, and the change from "boolean" to "Boolean".
It seems that "wait.getHealthy() == Boolean.TRUE" is always false, introduced in 0.25.0.
Comparison should be by value, not by reference.
Maven version : 3.5.4
JDK : 8
> Fix Boolean comparison for healthy option

- doc/changelog.md
- src/main/asciidoc/inc/_authentication.adoc
- src/main/java/io/fabric8/maven/docker/access/AuthConfig.java
- src/main/java/io/fabric8/maven/docker/config/RegistryAuthConfiguration.java
- src/main/java/io/fabric8/maven/docker/util/AuthConfigFactory.java
- src/test/java/io/fabric8/maven/docker/config/RegistryAuthConfigurationTest.java
- src/test/java/io/fabric8/maven/docker/util/AuthConfigTest.java
This allows extended ecr authentication to share the same token for pull and push requests.
See also #1286.
> fix(auth): Deprecate "authToken" in favor of "auth"

- pom.xml
- src/main/java/io/fabric8/maven/docker/util/AuthConfigFactory.java
- src/test/java/io/fabric8/maven/docker/util/AuthConfigFactoryTest.java
The feature to pick up [AWS credentials for Fargate tasks](https://docs.aws.amazon.com/AmazonECS/latest/userguide/task-metadata-endpoint-fargate.html) was introduced with #1235 
The same mechanism applies to [ECS-based tasks](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v2.html), but the composition of the URI is either slightly different or the underlying implementation more sensitive to the correctness of the URL: the current implementation of the plugin calculates `http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`, whereas `http://169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` would be appropriate for ECS-based tasks.
This PR extends the feature to work for both scenarios, and adds unit tests for both of them.
Instead of adding …
> Support both ECS & Fargate tasks

- doc/changelog.md
- src/main/asciidoc/inc/start/_configuration.adoc
- src/main/java/io/fabric8/maven/docker/access/DockerAccess.java
- src/main/java/io/fabric8/maven/docker/access/UrlBuilder.java
- src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java
- src/main/java/io/fabric8/maven/docker/config/RunImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/StopMode.java
- src/main/java/io/fabric8/maven/docker/config/WatchMode.java
- src/main/java/io/fabric8/maven/docker/service/ContainerTracker.java
- src/main/java/io/fabric8/maven/docker/service/RunService.java
- src/test/java/io/fabric8/maven/docker/service/RunServiceTest.java
Fix #1182 
This PR adds a parameter `stopMode` in RunImageConfiguration which accepts values `graceful` and `kill`. When doing `graceful` stop it would proceed with the usual process; In case of kill it would simply request docker daemon to kill the container.
Here are some API logs with stopMode being set to kill
```
~/work/repos/dmp-demo-project : $ mvn docker:stop -Ddocker.verbose=api,build
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< io.fabric8:dockerfile >------------------------
[INFO] Building dmp-sample-dockerfile 0.30-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- docker-maven-plugin:0.31-SNAPSHOT:stop (default-cli) @ dockerfile ---
[INFO] DOCKER> GETing unix://127.0.0.1:1/version
[INFO] …
```
> Fix #1182: Allow killing and removing all spawned containers

- src/main/asciidoc/inc/misc/_startup.adoc
…entryPoint>.
Per real-world experience and confirmed by RunImageConfiguration.java, typo in the documentation about the maven element name for overriding the image entry point.
> maven element for entry point is <entrypoint> not <entryPoint>

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java
- src/test/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClientTest.java
Fixes #838 
There are some scenarios that docker image with the same tag as the one created as temporary to be pushed to registry already exists. This could be the situation when image was tagged manually or pulled by some other process. Currently in this situation image will not be tagged and process will fail with exception.
After these changes 3 modes for handling of temporary images will be allowed:
- image of expected tag DOES exist - image with given tag will be updated and NOT removed after push,
- image of expected tag DOES NOT exist - tagged image will be treated as temporary and is removed after push,
- image push to registry failed - image will be tagged, because build was successful, but push failed.
#1170 already seems to try to solve this problem but it seems to be stale and …
> Warning, instead of exception, on temporary image existence

- .circleci/config.yml
As @rhuss pointed out in #1300 currently SonarCloud check shows that code coverage is 0% and does not meet Quality Gate of 80%.
After some time of trying to locate the issue I've noticed that jacoco profile is enabled neither for 'sonar' nor 'sonar-pr' CircleCI jobs.
It is worth noting that although changes made make sure that appropriate profile is enabled for both of those jobs, Quality Gate of 80% is not passed (it is 57.9% in my case) so it is worth to consider lowering it for the time being.
> Enable Jacoco profile for CircleCI Sonar-related jobs

- doc/changelog.md
- src/main/asciidoc/inc/_authentication.adoc
- src/main/java/io/fabric8/maven/docker/util/AuthConfigFactory.java
- src/test/java/io/fabric8/maven/docker/util/AuthConfigFactoryTest.java
With various AWS authentication mechanisms already in place, one of the most basic ones is yet missing: configuring credentials via environment variables.
See https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
> Pick up AWS credentials from ENV

- doc/changelog.md
- src/main/asciidoc/inc/build/_assembly.adoc
- src/main/java/io/fabric8/maven/docker/assembly/DockerFileBuilder.java
- src/main/java/io/fabric8/maven/docker/assembly/DockerFileKeyword.java
- src/test/java/io/fabric8/maven/docker/assembly/DockerFileBuilderTest.java
> Fix #544: Avoiding chown to reduce the image size

- doc/changelog.md
- src/main/asciidoc/inc/_global-configuration.adoc
- src/main/java/io/fabric8/maven/docker/BuildMojo.java
- src/main/java/io/fabric8/maven/docker/service/BuildService.java
- src/main/java/io/fabric8/maven/docker/service/WatchService.java
- src/test/java/io/fabric8/maven/docker/service/BuildServiceTest.java
- src/test/java/io/fabric8/maven/docker/service/LoadImageTest.java
Fix #1197 
with `docker.skip.build.image` flag we can skip pushing created docker archive to docker daemon.
> Fix #1197: Unable to build dockerFile without pushing it to docker server (DockerInDocker)

- src/main/java/io/fabric8/maven/docker/StopMojo.java
- src/main/java/io/fabric8/maven/docker/service/RunService.java
This PR adds an option to continue removing container and networks if one fails. A possible scenario is that the stop goal might try to remove multiple containers and one does not exist anymore (for whatever reason). This change will allow (with a new configuration option) to continue removing containers. The build will still fail though, to make the user aware of the problem.
> Add option to keep trying to remove containers, even if one fails

- pom.xml
Signed-off-by: Colm O hEigeartaigh <coheigea@apache.org>
This fixes the following CVE reports:
bcprov-jdk15on-1.57.jar (pkg:maven/org.bouncycastle/bcprov-jdk15on@1.57, cpe:2.3:a:bouncycastle:legion-of-the-bouncy-castle-java-crytography-api:1.57:*:*:*:*:*:*:*) : CVE-2017-13098, CVE-2018-1000180, CVE-2018-1000613
guava-23.0-android.jar (pkg:maven/com.google.guava/guava@23.0-android, cpe:2.3:a:google:guava:23.0:*:*:*:*:*:*:*) : CVE-2018-10237
snakeyaml-1.18.jar (pkg:maven/org.yaml/snakeyaml@1.18, cpe:2.3:a:snakeyaml_project:snakeyaml:1.18:*:*:*:*:*:*:*) : CVE-2017-18640
> Update BouncyCastle, Snakeyaml and Guava

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/util/CredentialHelperClient.java
- src/test/java/io/fabric8/maven/docker/util/CredentialHelperClientTest.java
This PR fixes #1348 by checking for the special username ```<token>``` that the docker login command uses to indicate the password is actually an authentication token.
> Handle authentication tokens returned from credential helpers.

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/StartMojo.java
- src/main/java/io/fabric8/maven/docker/service/WatchService.java
- src/main/java/io/fabric8/maven/docker/service/helper/StartContainerExecutor.java
- src/main/java/io/fabric8/maven/docker/util/AuthConfigFactory.java
- src/test/java/io/fabric8/maven/docker/service/helper/StartContainerExecutorTest.java
- src/test/java/io/fabric8/maven/docker/util/AuthConfigFactoryTest.java
Fix #1242 
Adding a `log.info(project.getProperties().toString()` in `StartMojo` seems to validate that properties are now getting set after this change.
```
~/work/repos/dmp-demo-project : $ mvn docker:start
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< io.fabric8:dockerfile >------------------------
[INFO] Building dmp-sample-dockerfile 0.30-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- docker-maven-plugin:0.33-SNAPSHOT:start (default-cli) @ dockerfile ---
[INFO] DOCKER> [test-db:latest] "rohankumar": Start container 77677e638894
[INFO] DOCKER> [test-db:latest] "rohankumar": Pausing for 5000 ms
[INFO] DOCKER> {docker.host.address=localhost, base=jetty, host.port=32772, project.artifactId=dockerfile, …
```
> Fix #1242: docker.container.<alias>.ip property is no longer set

- doc/changelog.md
- pom.xml
- samples/spring-boot-with-jib/README.md
- samples/spring-boot-with-jib/pom.xml
- samples/spring-boot-with-jib/src/main/java/io/fabric8/maven/sample/springboot/jib/Application.java
- samples/spring-boot-with-jib/src/main/java/io/fabric8/maven/sample/springboot/jib/HelloController.java
- samples/spring-boot-with-jib/static/testFile.txt
- src/main/asciidoc/inc/_global-configuration.adoc
- src/main/java/io/fabric8/maven/docker/AbstractBuildSupportMojo.java
- src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java
- src/main/java/io/fabric8/maven/docker/BuildMojo.java
- src/main/java/io/fabric8/maven/docker/PushMojo.java
- src/main/java/io/fabric8/maven/docker/assembly/BuildDirs.java
- src/main/java/io/fabric8/maven/docker/config/ImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/service/JibBuildService.java
- src/main/java/io/fabric8/maven/docker/service/ServiceHub.java
- src/main/java/io/fabric8/maven/docker/util/JibServiceUtil.java
- src/test/java/io/fabric8/maven/docker/service/JibBuildServiceTest.java
- src/test/java/io/fabric8/maven/docker/util/JibServiceUtilTest.java
This ports Jib support added in Eclipse JKube in https://github.com/eclipse/jkube/pull/257
> Support for JIB(Java Image Builder) mode in dmp

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/service/BuildService.java
- src/main/java/io/fabric8/maven/docker/util/DockerFileUtil.java
- src/test/java/io/fabric8/maven/docker/util/DockerFileUtilTest.java
Fix #1372 
Refactored `DockerFileUtil.extractBaseImages` to accept a HashMap of
Build args which would be passed from BuildService in order to resolve
ARG values which are provided from plugin configuration
> Fix #1372: Plugin now resolves ARGs provided in BuildImageConfiguration

- src/main/java/io/fabric8/maven/docker/util/DockerFileUtil.java
- src/test/java/io/fabric8/maven/docker/util/DockerFileUtilTest.java
Follow up PR for #1373 
Use regex in order to resolve ARG value
> Follow up PR for https://github.com/fabric8io/docker-maven-plugin/pull/1373

- .circleci/config.yml
- doc/changelog.md
- it/docker-compose/pom.xml
- it/dockerfile/pom.xml
- it/dockerfile/src/main/java/io/fabric8/dmp/samples/dockerfile/HelloWorldServlet.java
- it/dockerfile/src/main/webapp/WEB-INF/web.xml
- it/dockerignore/pom.xml
- it/healthcheck/pom.xml
- it/helloworld/pom.xml
- it/log/pom.xml
- it/net/pom.xml
- it/pom.xml
- it/properties/pom.xml
- it/run-java/pom.xml
- it/smallest/pom.xml
- it/spring-boot-with-jib/pom.xml
- it/spring-boot-with-jib/src/main/java/io/fabric8/maven/sample/springboot/jib/Application.java
- it/spring-boot-with-jib/src/main/java/io/fabric8/maven/sample/springboot/jib/HelloController.java
- it/volume/pom.xml
- it/zero-config/Dockerfile
- it/zero-config/pom.xml
- pom.xml
- src/main/asciidoc/inc/_global-configuration.adoc
- src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java
- src/main/java/io/fabric8/maven/docker/BuildMojo.java
- src/main/java/io/fabric8/maven/docker/service/JibBuildService.java
- src/main/java/io/fabric8/maven/docker/util/JibServiceUtil.java
- src/test/java/io/fabric8/maven/docker/util/JibServiceUtilTest.java
Fix #1384 
+ Updating jib-core to 0.15.0 broke our current JIB support due to
incompatibility with httpclient. Updated apache httpclient to 4.5.10
+ Somehow behavior of Jib setting ImageFormat has been changed(maybe it was
not working earlier. Introduced a new parameter in mojo `docker.build.jib.imageFormat`
to allow users specify image format(OCI or Docker) with Docker as
default ImageFormat.
+ Minor Cleanup in Integration tests; Added an integration test for JIB mode
which builds image tarball and verifies it by loading into docker daemon
This should also fix #1385
> Fix #1384: Building spring-boot-with-jib fails with NoSuchMethodEror

- src/main/asciidoc/inc/external/_property_configuration.adoc
- src/main/asciidoc/inc/start/_configuration.adoc
- src/main/java/io/fabric8/maven/docker/config/RunImageConfiguration.java
The documentation incorrectly stated that setting `memorySwap` to `-1` disables swap memory. This PR corrects that by describing how to disable swap (set `memorySwap` equal to `memory`) and that setting `memorySwap` to `-1` allows the container to use _unlimited_ swap.
See also https://docs.docker.com/config/containers/resource_constraints/#--memory-swap-details
Closes #1424
> Correct `memorySwap` documentation

- src/main/java/io/fabric8/maven/docker/access/hc/ApacheHttpClientDelegate.java
- src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java
- src/main/java/io/fabric8/maven/docker/access/hc/HcChunkedResponseHandlerWrapper.java
- src/test/java/io/fabric8/maven/docker/access/hc/ApacheHttpClientDelegateTest.java
- src/test/java/io/fabric8/maven/docker/access/hc/HcChunkedResponseHandlerWrapperTest.java
- fix: Valid content type for REST docker-compatible API requests with body
- fix: Push works with Podman REST API
This PR ports work done on eclipse/jkube#442 and eclipse/jkube#451 which allow the usage of Podman's REST API preventing the problems exposed in [this comment](https://github.com/fabric8io/docker-maven-plugin/issues/1330#issuecomment-667418730).
This video (using JKube instead) showcases how you would run JKube>DMP once the fix is merged: https://www.youtube.com/watch?v=hsomx014VPE
Relates to: #1330 eclipse/jkube#66
Most of the manual configuration can be now be avoided if using `podman-docker` package (`yum -y install podman-docker`) and enabling the podman.socket service (`systemctl enable --now podman.socket`)
> fix: Support for Podman REST API (when configured)

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
- src/test/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandlerTest.java
Fixes #1082 and fixes #1356 
This is based on the solution provided in #1082. I also added a test to show that the solution fixes the issue.
> Fix #1082 where `assembly.inline` is removed when external properties are enabled

- src/main/asciidoc/inc/_global-configuration.adoc
- src/main/java/io/fabric8/maven/docker/BuildMojo.java
- src/test/java/io/fabric8/maven/docker/BuildMojoTest.java
The usecase for this feature:
There are multiple projects which use the same docker-maven-plugin configuration. A logical way to extract that config to one place is to use the `pluginManagement` tag.
However, this leaves the need to define the plugin in every project wanting to use that configuration.
A ready solution is to define the plugin in the parent pom, but than the build will fail, because the docker build goal cannot find the packaged jar archive.
Here comes this PR, which tells the docker build goal to skip if the currently built project is a pom.
> Add a skipPom parameter, skipping a project if packaging is pom

- src/main/asciidoc/inc/_global-configuration.adoc
Fixed "Global Configuration" table in documentation - restored missing column in a row describing `skipPom` element. Refer to [that comment](https://github.com/fabric8io/docker-maven-plugin/pull/1388/files#r604321124) for details about the issue.
> Fix for "Global Configuration" table in documentation

- doc/changelog.md
- pom.xml
- src/main/java/io/fabric8/maven/docker/model/ContainerDetails.java
- src/main/java/io/fabric8/maven/docker/model/PortBindingException.java
- src/main/java/io/fabric8/maven/docker/service/RunService.java
- src/test/java/io/fabric8/maven/docker/model/ContainerDetailsTest.java
- src/test/java/io/fabric8/maven/docker/service/RunServiceTest.java
See https://github.com/fabric8io/docker-maven-plugin/issues/1446
Welcome feedback to my approach, to be frank I am not well versed with this code base and may have got some terminology wrong (especially in the unit test). If you can think of a better way to handle this I would love to hear it and happy to change the PR to implement.
On container startup, sometimes the port information retrieved from the
docker API is incomplete with port details being empty arrays, e.g.
Ports:{"2525/tcp":[]}. This causes an IndexOutOfBoundsException to be thrown
as the createPortBindings method assumes there will be at least one entry in
the mapping. In these cases we should retry the API call to get the more
complete port information.
Fixes #1446
> Avoid race condition when creating port bindings

- doc/changelog.md
- src/main/asciidoc/inc/start/_volumes.adoc
- src/main/java/io/fabric8/maven/docker/access/DockerConnectionDetector.java
- src/main/java/io/fabric8/maven/docker/util/DockerFileUtil.java
- src/main/java/io/fabric8/maven/docker/util/EnvUtil.java
- src/main/java/io/fabric8/maven/docker/util/VolumeBindingUtil.java
- src/test/java/io/fabric8/maven/docker/util/AuthConfigFactoryTest.java
The Java system property is filled by a syscall to determine the user's home directory. This is not matching the typical implementation of the docker and kubectl binaries, which prefer the HOME OS environment variable over the syscall.
> Prefer HOME environment variable

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/util/VolumeBindingUtil.java
- src/test/java/io/fabric8/maven/docker/util/VolumeBindingUtilTest.java
Hi this is a pull request for issue #1338 
I fixed only the specific issue I was having because when I tried to make the code more generic some tests were failing. The current code considers the initial rel of 'rel:/path/to/container/dir' as an absolute path which is not, when I tried to align the code considering rel as a relative some tests were failing and I do not have enough knowledge about this project in order to make a wider fix.
Fix #1338
> bug fix for Volume binding bug in windows #1338

- .github/workflows/linux-mavenwrapper-build.yml
- .github/workflows/windows-mavenwrapper-build.yml
- doc/changelog.md
Fix #1450 
+ Add Linux and Windows Github workflows for maven wrapper builds
+ Updated maven wrapper files as per maven 3.6.3
> Fix #1450: CI builds with Maven Wrapper to ensure that Maven Wrapper files and configuration are correct

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/util/ImageNameFormatter.java
- src/test/java/io/fabric8/maven/docker/util/ImageNameFormatterTest.java
Fix #1468 
This occurs when docker.image.name is constructed with `${docker.image.repo}:${docker.image.tag}`.
This is a fix to #1468
> If docker.image.tag is set to a placeholder, we should replace it.

- doc/changelog.md
- src/main/asciidoc/inc/_global-configuration.adoc
- src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java
- src/main/java/io/fabric8/maven/docker/util/AnsiLogger.java
- src/test/java/io/fabric8/maven/docker/BaseMojoTest.java
- src/test/java/io/fabric8/maven/docker/VolumeCreateMojoTest.java
- src/test/java/io/fabric8/maven/docker/VolumeRemoveMojoTest.java
This option is designed after:
https://maven.apache.org/plugins/maven-dependency-plugin/list-mojo.html#outputFile
Basically, it redirects the output logs to a file that can be processed by something else (another Mojo, external tools, etc.)
For context:
I'm working on Maven plugin that needs(in this case) to extract the pushed image `sha`.
> Add an option to dump the logs to an output file

- doc/changelog.md
- src/main/asciidoc/inc/build/_configuration.adoc
- src/main/asciidoc/inc/misc/_startup.adoc
- src/main/java/io/fabric8/maven/docker/service/BuildService.java
- src/test/java/io/fabric8/maven/docker/service/BuildServiceTest.java
First PR on this project, so not sure about processes and conventions.
I wasn't sure if this feature should have its own configuration or not. For me it makes sense to always try to pull the `cacheFrom` images in a non-failing way, while adhering to `config.imagePullPolicy`.
---
fixes https://github.com/fabric8io/docker-maven-plugin/issues/1457
> [1457] pull cacheFrom images during build

- doc/changelog.md
- src/main/asciidoc/inc/image/_naming.adoc
- src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/ImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/util/ImageNameFormatter.java
- src/test/java/io/fabric8/maven/docker/util/ImageNameFormatterTest.java
Fixes #1367
Allows replacement in tags and added a new replacement `%T` which always adds a timestamp, independent of the version.
> Allow replacements in build <tags>

- doc/changelog.md
- src/main/asciidoc/inc/misc/_startup.adoc
- src/main/java/io/fabric8/maven/docker/config/RunImageConfiguration.java
maven 3.6.3 error:
> Unable to parse configuration of mojo io.fabric8:docker-maven-plugin:0.37.0:start for parameter entryPoint: Cannot find 'entryPoint' in class io.fabric8.maven.docker.config.RunImageConfiguration
> inconsistent names of the `entryPoint` configuration parameter

- src/main/java/io/fabric8/maven/docker/StopMojo.java
Fix #915 
I tried several approaches and this hacky one worked. The problem is that the classloader of the Mojo is closed at the time of the shutdown hook.
What did not work:
- catching when maven session ends. It is removed from maven API since 3.x.
- creating a new URLClassLoader and using it as parent classloader of the Mojo ClassRealm. Some classes of Apache HTTPClient is already imported, so there is an error that not the same interface is implemented
This works as in case StartMojo was called before, only HttpDelete is not loaded by the classloader. In case no goal is called before this Mojo, more classes should be loaded programmatically, but I did not want to check how many, and by changing the dependencies, the list of classes could change.
Please check if this solution is OK for …
> Add support to stop docker containers during VM shutdown

- doc/changelog.md
- pom.xml
This should fix the UnsatisfiedLinkError on Apple M1 machines. [#1257](https://github.com/fabric8io/docker-maven-plugin/issues/1257)
If it had been possible I would have used a previous version number, to reduce side effects. But after updating some dependencies in the jnr-unixsocket projekt, 0.38.14 is the first version to make docker-maven-plugin work with native java on an apple silicon.
> chore: Update to jnr-unixsocket 0.38.14

- doc/changelog.md
- src/main/asciidoc/inc/build/_configuration.adoc
- src/main/asciidoc/inc/external/_property_configuration.adoc
- src/main/java/io/fabric8/maven/docker/TagMojo.java
- src/main/java/io/fabric8/maven/docker/access/DockerAccess.java
- src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java
- src/main/java/io/fabric8/maven/docker/service/BuildService.java
- src/test/java/io/fabric8/maven/docker/service/BuildServiceTest.java
There is a `cleanup` build configuration option that will by default 'cleanup dangling (untagged) images after each build'.
I would propose extending that to also cleanup dangling images as a result of:
tagging
auto-pulling of base images
auto-pulling of cache-from images
We use docker-maven-plugin on a CI server and auto-removing dangling images keeps the server from filling up with old image versions.
> Cleanup dangling images

- src/main/asciidoc/inc/build/_configuration.adoc
This adds the documentation that was missing from #1288
> Add docs about docker:build network config

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/service/BuildService.java
- src/test/java/io/fabric8/maven/docker/service/BuildServiceTest.java
Hi @rohanKanojia,
As a follow up to #1513, I've been testing a private build of the changes on our CI machines, and discovered a logic bug.
The condition to remove the image only if there are no other associated tags/repos should be reversed.
Additionally I'm looking to address one other scenario of dangling images.
That happens when pushing tags.
For example, the following code could result in a dangling image that will never be cleaned up, so I'm thinking of extending the logic to clean it up here as well.
```java
if (alreadyHasImage) {
log.warn("Target image '%s' already exists. Tagging of '%s' will replace existing image",
targetImage, fullName);
}
```
> Fix logic bug to remove dangling images

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/util/DockerFileUtil.java
- src/test/java/io/fabric8/maven/docker/util/DockerFileUtilTest.java
Fix #1528
See #1528 - will return the default value when `argMap.getValue() == null`
> [#1528] determineFinalArgValue respect default value if key exists but value is null

- src/main/java/io/fabric8/maven/docker/util/AuthConfigFactory.java
secDispatcher is not thread-safe, as it keeps some internal state when decrypting the password. This would make multi-thread maven builds sometimes.
With this, I believe that we could probably even annotate the mojos as threadSafe - at least I haven't found any further issues so far - but I also don't have a very deep knowledge of the code base.
> Prevent concurrent access to secDispatcher during password decryption

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/StopMojo.java
- src/test/java/io/fabric8/maven/docker/StopMojoTest.java
When command line contains -Ddocker.skip and stop goal configuration contains \<executeStopOnVMShutdown>true\</executeStopOnVMShutdown> the following code still throws an error:
```
if (!invokedTogetherWithDockerStart()) {
throw new MojoExecutionException("docker:stop with executeStopOnVMShutdown is only possible if" +
" the docker containers started within the same maven session.");
}
``` 
This execution should be skipped and there should not be an error.
> Stop should respect docker.skip

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/service/BuildXService.java
- src/test/java/io/fabric8/maven/docker/BuildMojoTest.java
- src/test/java/io/fabric8/maven/docker/MojoTestBase.java
According to the help-output of `docker buildx build --help`:
```
Usage:  docker buildx build [OPTIONS] PATH | URL | -
[...]
Options:
--add-host strings              Add a custom host-to-IP mapping (format: "host:ip")
--allow strings                 Allow extra privileged entitlement (e.g., "network.host", "security.insecure")
--build-arg stringArray         Set build-time variables
[...]
```
> Adds missing dash to --build-arg

- src/main/java/io/fabric8/maven/docker/service/BuildXService.java
- src/test/java/io/fabric8/maven/docker/BuildMojoTest.java
- src/test/java/io/fabric8/maven/docker/MojoTestBase.java
> When using buildx, do not force build of native platform

- src/main/java/io/fabric8/maven/docker/assembly/DockerAssemblyManager.java
- src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/ConfigKey.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
- src/main/java/io/fabric8/maven/docker/service/ArchiveService.java
- src/main/java/io/fabric8/maven/docker/service/BuildService.java
- src/main/java/io/fabric8/maven/docker/service/JibBuildService.java
- src/main/java/io/fabric8/maven/docker/service/WatchService.java
- src/test/java/io/fabric8/maven/docker/assembly/DockerAssemblyManagerTest.java
- src/test/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandlerTest.java
- src/test/java/io/fabric8/maven/docker/service/ArchiveServiceTest.java
- src/test/java/io/fabric8/maven/docker/service/BuildServiceTest.java
- src/test/java/io/fabric8/maven/docker/service/JibBuildServiceTest.java
- src/test/java/io/fabric8/maven/docker/service/WatchServiceTest.java
Fix #1558 
Fixes an issue #1558 where the way assemblies are gathered caused a singe inline configuration to be added twice and therefore causing incorrect error "Multiple assemblies use the name "maven". Please assign each assembly a unique name.".
> Issue #1558: Multiple assemblies use the name "maven". Please assign each assembly a unique name. - using only single assembly

- src/main/asciidoc/inc/_docker-build.adoc
This fixes the "5.1.6. Multi-Architecture Build" link on https://dmp.fabric8.io/. Currently it's linking to the healthcheck section.
> Fix documentation anchor for multiarch builds

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/access/ContainerHostConfig.java
- src/main/java/io/fabric8/maven/docker/config/RunImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/handler/compose/DockerComposeServiceWrapper.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
- src/test/java/io/fabric8/maven/docker/config/handler/compose/DockerComposeConfigHandlerTest.java
- src/test/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandlerTest.java
- src/test/java/io/fabric8/maven/docker/service/RunServiceTest.java
- src/test/resources/compose/docker-compose.yml
- src/test/resources/docker/containerCreateConfigAll.json
- src/test/resources/docker/containerHostConfigAll.json
Docker config option `--cpus` assumes float number, while current DMP `docker.cpus` assumes integer number, which is actually `NanoCpus`.
Change this property to `double` and convert it to `NanoCpus` before passing to Docker.
Signed-off-by: Vojtech Juranek <vojtech.juranek@gmail.com>
Fixes #1608
> Issue #1608: use double for docker.cpus property

- pom.xml
Maven verify `prerequisites.maven` before executing plugin 
so when you set lower version that used in code
some incompatibility can occur on older Maven.
Signed-off-by: Slawomir Jaranowski <s.jaranowski@gmail.com>
> Required Maven version should be the same as used Maven - 3.3.9

- doc/changelog.md
- it/build-pom-packaging/pom.xml
- it/pom.xml
- src/main/java/io/fabric8/maven/docker/BuildMojo.java
Default dependencies resolutions for Mojo is NONE.
When Mojo doesn't explicit required dependencies resolutions - plugins executed before can have impact on build.
Eg.
maven-enforcer-plugin only requires dependencies collections. If we have only m-enforcer-p like in pom packaging, resolved artifacts are not downloaded. It can cause NPE in m-assembly-p for missing files.
Fix #1146
> BuildMojo should require dependencies resolutions

- pom.xml
There are 1 security vulnerabilities found in org.yaml:snakeyaml 1.26
- [CVE-2022-25857](https://www.oscs1024.com/hd/CVE-2022-25857)
Upgrade org.yaml:snakeyaml from 1.26 to 1.32 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
Signed-off-by:pen4
> fix(sec): upgrade org.yaml:snakeyaml to 1.32

- doc/changelog.md
- pom.xml
There are 1 security vulnerabilities found in com.google.cloud.tools:jib-core 0.18.0
- [CVE-2022-25914](https://www.oscs1024.com/hd/CVE-2022-25914)
Upgrade com.google.cloud.tools:jib-core from 0.18.0 to 0.22.0 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
Signed-off-by:pen4<948453219@qq.com>
> fix(sec): upgrade com.google.cloud.tools:jib-core to 0.22.0

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/access/hc/HcChunkedResponseHandlerWrapper.java
- src/test/java/io/fabric8/maven/docker/access/hc/HcChunkedResponseHandlerWrapperTest.java
Fix https://github.com/fabric8io/docker-maven-plugin/issues/1598
Instead of always buffering the response, stream the response to the handler if the headers indicate it is definitely JSON.  Buffer like before if there are no content-type headers and the body needs to be checked.
This will allow pull progress to be displayed in real time for all situations where there is a JSON content type, which would be for the majority of cases.
> Avoid buffering and stream the response if the headers indicate it is JSON

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/BuildMojo.java
- src/main/java/io/fabric8/maven/docker/service/BuildXService.java
- src/main/java/io/fabric8/maven/docker/service/RegistryService.java
- src/test/java/io/fabric8/maven/docker/service/RegistryServiceTest.java
`repository` should be used when pushing multi-arch images with buildx.
repository (config and docker.push.registry)was ignored when using buildx  and instead, the default Docker Hub was used and yielded the the following error `error: failed to solve: server message: insufficient_scope: authorization failed` 
Fixes #1597 #1593 
Signed-off-by: Peter Merikan <peter@merikan.com>
> fix: multi-arch build should use provided repository

- doc/changelog.md
- src/main/asciidoc/inc/external/_property_configuration.adoc
- src/main/java/io/fabric8/maven/docker/config/handler/property/ConfigKey.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
The configuration of
```
<images>
<image>
<name>xx/%a:%l</name>
<alias>xxxx</alias>
<build>
<dockerFile>${project.basedir}/Dockerfile</dockerFile>
<network>host</network>
</build>
<external>
<type>properties</type>
<prefix>docker</prefix>
<mode>override</mode>
</external>
</image>
</images>
```
simply does not propagate the network option further. When omitting "external" it works as expected. The network field is not resolved when external configuration resolution takes place.
Network field was introduced in https://github.com/fabric8io/docker-maven-plugin/pull/1288
> Allow overriding build network from properties

- doc/changelog.md
- pom.xml
> deps : Update Jnr UnixSocket to v0.38.19

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/service/JibBuildService.java
- src/main/java/io/fabric8/maven/docker/util/JibServiceUtil.java
- src/test/java/io/fabric8/maven/docker/service/JibBuildServiceTest.java
Fix #1617 
JibBuildService should check all available registry options before submitting ImageConfiguration to Jib.
> fix : Jib ignores `DOCKER_REGISTRY` environment variable (#1617)

- doc/changelog.md
- pom.xml
Use our own latest version of `com.github.jnr:jffi` dependency
> chore (deps) : Update Jnr Jffi dependency to v1.3.11 (#1660)

- doc/changelog.md
- src/main/asciidoc/inc/build/_buildx.adoc
- src/main/java/io/fabric8/maven/docker/service/BuildXService.java
- src/test/java/io/fabric8/maven/docker/service/BuildXServiceTest.java
This PR enables building a single-platform image with an architecture that differs from the native platform.  For example, if you're build machine is an arm M1 but you need to test and deploy amd64.  Note that while docker currently does not support multi-architecture images in the local image cache, it will use emulation to run e.g. an amd64 image on an arm host.
This is in follow up to https://github.com/fabric8io/docker-maven-plugin/issues/1557#issuecomment-1503976990
> change buildAndLoadNativePlatform to buildAndLoadSinglePlatform

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/access/ContainerHostConfig.java
- src/test/java/io/fabric8/maven/docker/access/ContainerHostConfigTest.java
Fixes #1527
On macOS and Windows docker provides out-of-the-box an alias `host.docker.internal`, however not on Linux.
`host.docker.internal` is easy in case a running container needs to talk back to a TCP/UDP socket on the docker host.
Since docker 20.10.x they have added the ability to add an extra host using a magic hostname `host-gateway`.
This PR detects this, and does not attempt to resolve the hostname, but passes it on to docker.
This also works on macOS and Windows, and gives even the opportunity to use another alias, instead of `host.docker.internal`.
> GH-1527 allow 'host-gateway' as non-resolvable hostname in extraHosts

- src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java
- src/test/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClientTest.java
Fix #1690
when "RepoTags" that is from "docker inspect" is null, check it.
> FIX: Not a JSON Array: null

- src/main/java/io/fabric8/maven/docker/BuildMojo.java
- src/main/java/io/fabric8/maven/docker/access/AuthConfig.java
- src/main/java/io/fabric8/maven/docker/access/AuthConfigList.java
- src/main/java/io/fabric8/maven/docker/service/BuildXService.java
- src/main/java/io/fabric8/maven/docker/service/RegistryService.java
- src/test/java/io/fabric8/maven/docker/BuildMojoTest.java
- src/test/java/io/fabric8/maven/docker/MojoTestBase.java
- src/test/java/io/fabric8/maven/docker/access/AuthConfigListTest.java
- src/test/java/io/fabric8/maven/docker/assembly/TrackArchiverCollectionTest.java
- src/test/java/io/fabric8/maven/docker/service/BuildXServiceTest.java
- src/test/resources/docker/Dockerfile.custom_registry.test
This addresses a `401 Unauthorized` error when building for multi-platform and multiple credentials are needed for different registries. For example, if the image name is `registry-one.org/library/example` and the base (`FROM`) image is in another registry (e.g. `registry-two.org`), two credentials are needed: one for each registry.
I believe this would also fix https://github.com/fabric8io/docker-maven-plugin/issues/1583 .
> Fix unauthorized error with buildx needing multiple credentials

- src/main/java/io/fabric8/maven/docker/service/WaitService.java
- src/main/java/io/fabric8/maven/docker/wait/HttpPingChecker.java
- src/test/java/io/fabric8/maven/docker/util/WaitUtilTest.java
- src/test/java/io/fabric8/maven/docker/wait/HttpPingCheckerTest.java
Adds logging to HTTP wait checker. Also added a test for this class.
> Add logger to HTTP ping checker

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/service/BuildXService.java
- src/test/java/io/fabric8/maven/docker/BuildMojoTest.java
- src/test/java/io/fabric8/maven/docker/service/BuildXServiceTest.java
- src/test/java/io/fabric8/maven/docker/service/RegistryServiceTest.java
As per this comment: 
https://github.com/fabric8io/docker-maven-plugin/issues/1583#issuecomment-1537097053
removing the "--config" let the sample project "multi-architecture" to build fine
> Make `--config` from buildx command string generation optional

- doc/changelog.md
- it/buildx-push/Dockerfile
- it/buildx-push/pom.xml
- it/pom.xml
- src/main/java/io/fabric8/maven/docker/BuildMojo.java
- src/main/java/io/fabric8/maven/docker/access/AuthConfigList.java
- src/main/java/io/fabric8/maven/docker/service/BuildXService.java
- src/main/java/io/fabric8/maven/docker/util/AuthConfigFactory.java
- src/test/java/io/fabric8/maven/docker/BuildMojoTest.java
- src/test/java/io/fabric8/maven/docker/PushMojoBuildXTest.java
- src/test/java/io/fabric8/maven/docker/access/AuthConfigListTest.java
- src/test/java/io/fabric8/maven/docker/service/BuildXServiceTest.java
- src/test/java/io/fabric8/maven/docker/service/RegistryServiceTest.java
- src/test/java/io/fabric8/maven/docker/util/AuthConfigFactoryTest.java
Related to #1698
+ Add null checks for authConfig and fromRegistry in BuildMojo
+ Change condition for adding --config option to docker buildx. Temporary config.json file seems to be getting created after we already add config flag. Since this option seems to be useful only when credentials are coming from outside sources (settings, properties, etc); don't add --config when it's coming from local docker config.json
+ Add integration test for docker buildx push that uses `ttl.sh` anonymous registry
> fix (buildx) : Do not use `--config` when registry credentials from local docker config

- doc/changelog.md
- src/main/asciidoc/inc/build/_buildx.adoc
- src/main/java/io/fabric8/maven/docker/config/BuildXConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/ConfigKey.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
- src/main/java/io/fabric8/maven/docker/service/BuildXService.java
- src/test/java/io/fabric8/maven/docker/PushMojoBuildXTest.java
Address the issue pointed out by @amizurov in https://github.com/fabric8io/docker-maven-plugin/pull/1673#issuecomment-1656699361
+ Instead of using a hardcoded value, node should be configurable by the new configuration option `buildx` > `nodeName`
> fix (buildx) : Remove hardcoded `--node` value while creating buildx …builder

- doc/changelog.md
- src/main/asciidoc/inc/build/_buildx.adoc
- src/main/java/io/fabric8/maven/docker/service/BuildXService.java
- src/test/java/io/fabric8/maven/docker/BuildMojoTest.java
- src/test/java/io/fabric8/maven/docker/PushMojoBuildXTest.java
- src/test/java/io/fabric8/maven/docker/service/BuildXServiceDockerVersionExternalCommandTest.java
- src/test/java/io/fabric8/maven/docker/service/BuildXServiceTest.java
- src/test/java/io/fabric8/maven/docker/service/RegistryServiceTest.java
+ Always pass --config option in case of latest docker CLI (>= 23.0.x)
+ Change default value of `--node` parameter to null
> fix (buildx) : Always pass --config option for latest versions of Docker CLI (#1701)

- doc/changelog.md
- src/main/asciidoc/inc/build/_configuration.adoc
- src/main/java/io/fabric8/maven/docker/assembly/DockerAssemblyManager.java
- src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/ConfigKey.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
This commit introduces a new build parameter, "defaultExclusion," within the build properties of the plugin. The current behavior of the plugin is to build a Docker archive with default exclusion rules, which exclude hidden files. However, the Docker CLI includes hidden files by default.
With the addition of the "defaultExclusion" parameter, users can now control whether hidden files should be excluded during the Docker archive build process. This parameter provides flexibility and allows users to align the plugin's behavior with their specific requirements.
Fixes: https://github.com/fabric8io/docker-maven-plugin/issues/1708
> Add new build parameter: "defaultExclusion"

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/config/ConfigHelper.java
- src/main/java/io/fabric8/maven/docker/service/BuildService.java
- src/main/java/io/fabric8/maven/docker/service/BuildXService.java
- src/test/java/io/fabric8/maven/docker/service/BuildXServiceTest.java
Heya, I noticed that running a multiplatform build (which uses buildx) ignores the configured no-cache directive. e.g. this pom.xml
```
<configuration>
<pullRegistry>docker.io</pullRegistry>
<pushRegistry>${docker.registry}</pushRegistry>
<images>
<image>
<name>blah</name>
<build>
<noCache>true</noCache>
<buildx>
<platforms>
<platform>linux/arm64</platform>
<platform>linux/amd64</platform>
</platforms>
</buildx>
<contextDir>${project.basedir}/target/dockercontext</contextDir>
</build>
</image>
</images>
</configuration>
```
was not actually passing down `--no-cache` to the buildx command.
This PR causes the top-level build option to be passed down to buildx if buildx happens to be used. Note that the check for no-cache is copy-pasted from your existing implementation. I didn't want to do …
> Add no-cache functionality into Buildx.

- doc/changelog.md
- it/buildx-dockerfile_and_contextdir/Dockerfile
- it/buildx-dockerfile_and_contextdir/pom.xml
- it/buildx-dockerfile_and_contextdir/src/docker/resource.properties
- it/pom.xml
- src/main/java/io/fabric8/maven/docker/service/BuildXService.java
Fixes a Buildx build failure when an external Dockerfile outside of the Docker build context directory is specified.
The Dockerfile (be it an external one or the generated one) is always stored at the root of the build archive created by  `DockerAssemblyManager.createDockerTarArchive()`.
Before this patch the code which constructs the full path of the Dockerfile to pass to Buildx didn't take that into account.
> Fix Buildx build with Dockerfile outside of Docker build context

- it/dockerfile-base-as-arg/README.md
- it/dockerfile-base-as-arg/pom.xml
- it/dockerfile-base-as-arg/src/main/docker/Dockerfile
- it/dockerfile-base-as-arg/src/main/docker/welcome.txt
- it/dockerfile-base-as-arg/src/main/java/io/fabric8/dmp/samples/dockerfile/HelloWorldServlet.java
- it/dockerfile-base-as-arg/src/main/webapp/WEB-INF/web.xml
- it/pom.xml
- src/main/java/io/fabric8/maven/docker/service/BuildService.java
Scenario: build using a Dockerfile, I'm trying to configure the base image using an ARG, as in:
```
ARG baseImage=some/project:version
FROM $baseImage
...
```
This works as long as I don't want a different base image, or if I configure it in the image settings. In theory `docker.buildArg.baseImage=ghcr.io/some/otherProject:otherVersion` should allow changing that value, but that doesn't work since the `autoPullBaseImage` code only looks in the image buildArg configuration.
This PR adds support for looking at all the arg configurations, no matter where they're coming from.
> Add support for using maven/system properties for an ARG used as the FROM image in a dockerfile

- doc/changelog.md
- it/buildx-driver-opt/pom.xml
- it/buildx-driver-opt/src/main/java/io/fabric8/dmp/sample/multiarch/helloworld/App.java
- src/main/asciidoc/inc/build/_buildx.adoc
- src/main/java/io/fabric8/maven/docker/config/BuildXConfiguration.java
- src/main/java/io/fabric8/maven/docker/service/BuildXService.java
- src/test/java/io/fabric8/maven/docker/service/BuildXServiceCreateBuilderTest.java
I recently had a use case where I wanted to change the builder image name to use an image from our local Artifactory instance.
To do that with the builder, I needed to add support for driverOpts to set  `--driver-opt image=MY_IMAGE`. Tested locally, seems to work fine.
Regarding testing - I did not see any tests currently verifying the buildx create.
https://docs.docker.com/engine/reference/commandline/buildx_create/#driver-opt
> Add support setting driverOpts for buildx

- .github/workflows/sonar-pr.yml
- .github/workflows/sonar.yml
Sonar now requires Java 17 for doing analysis.  Read more about this here[0]
Bump Sonar workflow JDK to Java 17.
[0] https://community.sonarsource.com/t/java-11-is-deprecated-as-a-runtime-env-to-scan-your-projects/96597
> ci : Move Sonar analysis to Java 17

- src/main/java/io/fabric8/maven/docker/SourceMojo.java
Hello Maintainers,
I just wanted to let you know that I have modified the code. I have changed the `imageConfigs>0` to `!imageConfigs.isEmpty()` to check whether the Collection is empty. After making these changes, I have used the `mvn clean install` command.
Best Regards,
@mdxabu
> Fix: SourceMojo: Use `isEmpty()` to check whether collection is empty or not issue1746

- .github/workflows/e2e-tests.yml
- .github/workflows/e2e-windows.yml
- .github/workflows/macos-mavenwrapper-build.yml
- it/pom.xml
- it/windows-build/pom.xml
+ Use `crazy-max/ghaction-setup-docker` GitHub action to run E2E tests tied to a specific version of Docker
+ Add a minimal E2E test for windows that would just verify that DMP is able to build image with docker on windows
+ Add build job for verifying project compiles on Mac OS
> ci : Run E2E tests against multiple versions of Docker

- pom.xml
We bumped `maven.version` in #1702 to `3.8.1` that broke compatibility with maven < `3.8.1 `. Add a property `minimum.maven.version` to keep minimum supported maven version.
> chore : prerequisite maven version should be different from maven version

- .github/workflows/release-snapshots.yml
- README.md
- doc/HowToUseDockerMavenPluginSnapshotArtifacts.md
- pom.xml
Add GitHub action workflow to do nightly builds and publish SNAPSHOT artifacts at maven central. This would help us get early feedback from users before doing releases.
Release pipeline is taken from [Fabric8 Kubernetes Client Release Snapshot GitHub Action Workflow](https://github.com/fabric8io/kubernetes-client/blob/main/.github/workflows/release-snapshots.yaml)
> ci : Enable publishing snapshot artifacts to maven central

- .github/workflows/e2e-tests.yml
- .github/workflows/e2e-windows.yml
- it/multi-assembly/pom.xml
+ Enable E2E tests to run on GitHub MacOS runners
+ Use `crazy-max/ghaction-setup-docker` action to set up docker on MacOS
> ci : E2E tests should also run on GitHub MacOS runners

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/AbstractBuildSupportMojo.java
- src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java
- src/main/java/io/fabric8/maven/docker/BuildMojo.java
- src/main/java/io/fabric8/maven/docker/PushMojo.java
- src/main/java/io/fabric8/maven/docker/service/RegistryService.java
- src/test/java/io/fabric8/maven/docker/PushMojoTest.java
- src/test/java/io/fabric8/maven/docker/service/RegistryServicePushImagesBuildXTest.java
- src/test/java/io/fabric8/maven/docker/service/RegistryServiceTest.java
Fix #1709 
+ During BuildX push we also need credentials for pulling base images used in Dockerfile. Sending a single AuthConfig just for push registry will not work. 
+ Refactor code in BuildMojo to extract AuthConfig for base images used in Build configuration / Dockerfile . Move common logic as static methods in RegistryService so that it can be reused in both build and push goals.
> fix : AuthConfigList is populated with from images during buildx push as well

- src/main/java/io/fabric8/maven/docker/model/ContainerDetails.java
- src/main/java/io/fabric8/maven/docker/model/ContainersListElement.java
Dear Maintainers,
I wanted to inform you that I have made some modifications in two files: `ContainersListElements.java` and `ContainerDetails.java`. Specifically, I have changed the `while` loop to an `enhanced for` loop and altered the `if` statement to a `ternary` statement.
Best regards,
F Mohamed Abdullah
> Fix: Changed  statement like while to enhanced for loop and `if` to ternary operator

- samples/spring-boot-with-jib/pom.xml
> #1762 - Upgrading spring to 2.7.18 for spring-boot-with-jib sample

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/access/PortMapping.java
- src/test/java/io/fabric8/maven/docker/access/PortMappingPropertyWriteHelperTest.java
This adds a new option enabling automatic folder creation for the path specified in `portPropertyFile`.
> Feat: Automatically create parent directories of portPropertyFile path

- src/main/java/io/fabric8/maven/docker/access/log/LogRequestor.java
- src/test/java/io/fabric8/maven/docker/access/log/LogRequestorTest.java
Dear @rohanKanojia ,
I wanted to inform you that I have made a change in the code. The `Charset.UTF_8` has been replaced with `StandardCharsets.UTF_8`.
Best Regards,
F Mohamed Abdullah
> Fix: LogRequestor : Replaced `com.google.common.base.Charsets.UTF_8` with `StandardCharsets.UTF_8` 

- src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java
I don't understand the reason to limit the image id. This works on Podman and Docker.
> Issue #1763 & #1676

- src/main/java/io/fabric8/maven/docker/service/WatchService.java
Dear @rohanKanojia ,
I have made the changes as you requested. The `new Runnable()` has been changed to a `lambda` function.
> Update: WatchService : Anonymous `new Runnable()` can be replaced with lambda

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/config/handler/compose/DockerComposeConfigHandler.java
- src/main/java/io/fabric8/maven/docker/config/handler/compose/DockerComposeServiceWrapper.java
- src/test/java/io/fabric8/maven/docker/config/handler/compose/DockerComposeConfigHandlerTest.java
- src/test/resources/compose/docker-compose_2.4.yml
On Mac M1 docker-maven-plugin when using external docker-compose.yml configuration produces the following error:
```
I/O Error: Unable to create container for [...] : {"message":"image with reference ... was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64"} (Not Found: 404)
```
The solution is to add platform declaration to each service image:
```
services:
alias1:
image: host/org/image:1.0.0
platform: linux/amd64
```
which overrides the native platform value `linux/arm64` used by default. Unfortunately, the `platform` field in docker-compose config was ignored. This PR fixes that.
PS: Virtualization on Mac allows running amd64 build images.
> Support platform in external docker-compose config

- src/main/java/io/fabric8/maven/docker/config/handler/compose/DockerComposeServiceWrapper.java
Fix #1779
> Inside [DockerComposeServiceWrapper.java](https://github.com/fabric8io/docker-maven-plugin/blob/fc53963fc57c466dc10757ac98d2009927f6ef15/src/main/java/io/fabric8/maven/docker/config/handler/compose/DockerComposeServiceWrapper.java#L407-L412) made below changes addrssing issue #1779
> Update:  size > 0 check  to isEmpty method and rename configuration field

- src/main/java/io/fabric8/maven/docker/util/AnsiLogger.java
- src/test/java/io/fabric8/maven/docker/util/AnsiLoggerTest.java
Init of Ansi system is not needed in Maven plugin.
Additionally, Maven 4 switch to JLine
https://issues.apache.org/jira/browse/MNG-7995
and this class will be not available anymore
> Remove usage of AnsiConsole

- it/graceful-container-removal/pom.xml
- it/pom.xml
- src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java
If a container is to be removed - yet doesn't exist anymore, we can gracefully handle the 404 by treating it as though the container had been removed.
> Gracefully handle 404 when removing container

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/util/DockerFileUtil.java
- src/test/java/io/fabric8/maven/docker/util/DockerFileUtilTest.java
- src/test/resources/io/fabric8/maven/docker/util/Dockerfile_from_simple_with_args
- src/test/resources/io/fabric8/maven/docker/util/Dockerfile_from_simple_with_chained_args
> fix: arg stated in a FROM clause can reference other args (#1800)

- doc/changelog.md
- it/buildx-dockerfile-secret/pom.xml
- it/buildx-dockerfile-secret/src/main/docker/Dockerfile
- it/pom.xml
- src/main/asciidoc/inc/build/_buildx.adoc
- src/main/java/io/fabric8/maven/docker/config/BuildXConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/SecretConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/ConfigKey.java
- src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
- src/main/java/io/fabric8/maven/docker/service/BuildXService.java
- src/test/java/io/fabric8/maven/docker/BuildMojoTest.java
> feature: Add the possibility to give secret to buildx build (#1798)

- .github/workflows/doc-build.yml
Make use of `actions/deploy-pages` and `actions/upload-pages-artifact` workflows to deploy project website to GitHub pages
> ci : Fix documentation deploy pipeline

- .github/workflows/release.yml
This is taken from [Fabric8 Kubernetes Client release pipeline](https://github.com/fabric8io/kubernetes-client/blob/main/.github/workflows/release.yaml)
It would take input of release tag and perform release of project at that specific revision. There are some additional inputs as well with java version and additional_args (for release).
> ci : Add a pipeline for release to maven central

- .github/workflows/e2e-tests.yml
Add recent docker releases to E2E tests matrix
> ci : Add Docker versions v27.1.1 and v26.1.4 to E2E tests matrix

- src/main/java/io/fabric8/maven/docker/util/VolumeBindingUtil.java
Fixes https://github.com/fabric8io/docker-maven-plugin/issues/1813
This pull request resolves the mentioned issue by updating the volumeBinding list iteration and set operation by using Java's built-in replaceAll method.
> refactor: replace list iteration with List.replaceAll method

- src/main/java/io/fabric8/maven/docker/service/BuildService.java
- src/test/java/io/fabric8/maven/docker/MojoTestBase.java
- src/test/java/io/fabric8/maven/docker/service/BuildServiceTest.java
> Pull FROM images in relative path Dockerfiles

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/service/BuildXService.java
- src/test/java/io/fabric8/maven/docker/service/BuildXServiceTest.java
Fix https://github.com/fabric8io/docker-maven-plugin/issues/1818
> BuildX failing for Docker CLI on Windows fixed

- samples/build-cache/README.md
- samples/build-cache/app/pom.xml
- samples/build-cache/image/pom.xml
- samples/build-cache/image/src/main/docker/Dockerfile
- samples/build-cache/pom.xml
Update of example introduced in #1412 to make it compatible with recent versions of Docker Engine (tested on 19.03.12 and 27.1.1).
> Docker build cache friendly example updated

- doc/changelog.md
- it/docker-compose-dependon/docker-compose.yml
- src/main/asciidoc/inc/external/_docker_compose.adoc
- src/main/asciidoc/inc/start/_configuration.adoc
- src/main/java/io/fabric8/maven/docker/StartMojo.java
- src/main/java/io/fabric8/maven/docker/access/ContainerCreateConfig.java
- src/main/java/io/fabric8/maven/docker/access/util/ComposeDurationUtil.java
- src/main/java/io/fabric8/maven/docker/config/RunImageConfiguration.java
- src/main/java/io/fabric8/maven/docker/config/handler/compose/DockerComposeConfigHandler.java
- src/main/java/io/fabric8/maven/docker/config/handler/compose/DockerComposeServiceWrapper.java
- src/main/java/io/fabric8/maven/docker/service/RunService.java
- src/main/java/io/fabric8/maven/docker/service/WaitService.java
- src/test/java/io/fabric8/maven/docker/access/ContainerCreateConfigTest.java
- src/test/java/io/fabric8/maven/docker/access/util/ComposeDurationUtilTest.java
- src/test/java/io/fabric8/maven/docker/config/handler/compose/DockerComposeConfigHandlerTest.java
- src/test/java/io/fabric8/maven/docker/service/RunServiceTest.java
- src/test/resources/compose/docker-compose.yml
- src/test/resources/compose/docker-compose_healthcheck.yml
- src/test/resources/docker/containerCreateConfigAll.json
- Docker-compose `healthcheck` configuration support
- Docker container wait timeout default value made configurable using `startContainerWaitTimeout` configuration option
> healthcheck support in docker-compose configuration

- src/main/java/io/fabric8/maven/docker/StopMojo.java
I encountered the following issue:
Using:
```
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: C:\Program Files\apache-maven
Java version: 17.0.12, vendor: Eclipse Adoptium, runtime: C:\Program Files\Java\jdk-17.0.12+7
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
Adding the two required classes to the Class loader resolved the issue. I didn't go in too deep why that check using Strings occurs.
Here's the execution config which lead to this:
```xml
<execution>
<id>remove-it-database</id>
<goals>
<goal>stop</goal>
</goals>
<configuration>
<executeStopOnVMShutdown>true</executeStopOnVMShutdown>
<removeVolumes>true</removeVolumes>
<skip>${skipTests}</skip>
</configuration> …
```
> Fix for missing classes required on executeStopOnVMShutdown:true

- .github/workflows/e2e-tests.yml
- pom.xml
+ Add same version of sonar-maven-plugin as used in jkube
+ Use v3 version of setup-docker github action in e2e macOS pipelines
> ci : fix failing sonar and E2E macOS github action workflows

- pom.xml
- src/main/java/io/fabric8/maven/docker/util/AuthConfigFactory.java
- src/test/java/io/fabric8/maven/docker/PushMojoBuildXTest.java
- src/test/java/io/fabric8/maven/docker/util/AuthConfigFactoryTest.java
Use the "official" way instead, and it solves Maven 4 support as well.
Changes:
* align Maven deps (maven-compat was 3.0 while maven-core 3.8.1)
* since Maven 3.9 plexus util is NOT provided
* do not use directly SecDispatcher, use Maven APIs instead
* fix UTs
> Move off direct SecDispatcher use

- src/main/asciidoc/inc/_docker-stop.adoc
I believe it works the same as v option https://docs.docker.com/reference/api/engine/version/v1.43/#tag/Container/operation/ContainerDelete so it doesn't remove "any" containers only the anonymous ones.
> docs: Correct removeVolumes description

- doc/changelog.md
- src/main/java/io/fabric8/maven/docker/config/ConfigHelper.java
- src/main/java/io/fabric8/maven/docker/service/BuildXService.java
- src/test/java/io/fabric8/maven/docker/service/BuildXServiceTest.java
I have found that the configuration of the network (in Docker with the parameter `--network`) is not respected in multi-arch builds using `buildx`. One can configure the network as stated in the documentation, however, this has no effect on the commandline call of `docker`.
The reason is that the configuration of `network` is simply not considered.
I provided a unit tests which shows the problem and a fix that considers the configuration done via System properties, Maven properties, and in the configuration of the plugin.
> fix: respects network configuration for buildx

- .github/workflows/e2e-tests.yml
- src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java
- src/main/java/io/fabric8/maven/docker/util/ContainerNamingUtil.java
- src/main/java/io/fabric8/maven/docker/util/CredentialHelperClient.java
- src/main/java/io/fabric8/maven/docker/util/ImageNameFormatter.java
- src/main/java/io/fabric8/maven/docker/util/JibServiceUtil.java
@rohanKanojia, This PR refactors several classes by replacing Guava-specific collections and utilities with their corresponding Java Standard Library counterparts #1834. The following changes have been made:
- **`AbstractDockerMojo.java`**: 
- I replaced `ImmutableList` with `List` and used `ArrayList` to build the list and `Collections.unmodifiableList` for immutability.
- **`ContainerNamingUtil.java`**: 
- I replaced `ImmutableSet` with `HashSet` and switched to `Collections.unmodifiableSet` for immutability.
- **`CredentialHelperClient.java`**:
- I replaced Guava's `Joiner` with `String.join()` and `Lists.newLinkedList()` with `new LinkedList<>()`.
- **`ImageNameFormatter.java`**:
- I replaced Guava's `Strings.isNullOrEmpty()` with `String.isNullOrEmpty()`.
- **`JibServiceUtil.java`**: …
> issue #1834: Refactor to Replace Guava with JDK Built-In Functionalities

- .github/workflows/doc-build.yml
Documentaiton pipeline is failing https://github.com/fabric8io/docker-maven-plugin/actions/runs/14295932021
bump github action upload-artifact version to v4 to fix failure.
> ci : fix docs pipeline by updating github action upload-artifact to latest version

- src/main/java/io/fabric8/maven/docker/TagMojo.java
> Issue #1870 - dmp:tag should skip <image>s with no <build>

- src/main/asciidoc/inc/build/_buildx.adoc
- src/main/java/io/fabric8/maven/docker/service/BuildXService.java
- src/test/java/io/fabric8/maven/docker/BuildMojoTest.java
> #1804 support buildx use of default builder

- .github/workflows/release-snapshots.yml
- pom.xml
CI Pipeline to push SNAPSHOTs is failing:
```
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact io.fabric8:docker-maven-plugin:jar.asc:0.47-20250618.031628-53 from/to sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots/): Authorization failed for https://oss.sonatype.org/content/repositories/snapshots/io/fabric8/docker-maven-plugin/0.47-SNAPSHOT/docker-maven-plugin-0.47-20250618.031628-53.jar.asc 403 Forbidden
```
Migrate SNAPSHOT release pipeline to the new Central Portal.
> ci : Update release snapshots configuration after Fabric8 namespace migration to central portal

- .github/workflows/sonar-pr-analysis-publish.yml
- pom.xml
Bump test dependencies to latest available version
- junit.jupiter.version: 5.8.2 → 5.10.0
- mockito.version: 4.5.1 → 4.11.0
- surefire.version: 3.5.2 → 3.5.3
- assertj-core.version: 3.25.3 → 3.27.3
All updates maintain JDK 8 compatibility.
> chore (deps) : Bump test dependencies to latest available versions (JUnit, Mockito, Surefire, AssertJ, System Stubs)
